### ISSUE TITLE
无法进行黑域，以下为log

### ISSUE THREAD

**Issue by Luwattz** [brevent/Brevent#114]
checking for server....started, pid: 10303
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '07-18 22:21:30.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '07-18 22:21:30.000' -d -s BreventLoader BreventServer
07-18 22:21:32.820 10236 10236 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
07-18 22:21:33.907 10303 10303 D BreventServer: get service: package
07-18 22:21:33.909 10303 10303 D BreventServer: args: [10]
07-18 22:21:33.909 10303 10303 I BreventServer: signal: 10
07-18 22:21:33.913 10303 10303 I BreventServer: starting Brevent Server 2.0.1
07-18 22:21:33.936 10303 10303 D BreventServer: get service: package
07-18 22:21:33.958 10303 10303 I BreventServer: brevent user: 0, uid: 2000
07-18 22:21:33.962 10303 10303 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-18 22:21:34.042 10303 10303 I BreventServer: loading brevent list
07-18 22:21:34.077 10303 10303 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 70
07-18 22:21:34.091 10303 10303 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 22:21:34.091 10303 10303 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.remove(java.lang.Object)' on a null object reference
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:1130)
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.e(BreventServer.java:392)
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:246)
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:1975)
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2041)
07-18 22:21:34.091 10303 10303 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
07-18 22:21:34.091 10303 10303 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2126)
07-18 22:21:34.091 10303 10303 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-18 22:21:34.091 10303 10303 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:262)
07-18 22:21:34.163 10236 10236 E BreventLoader: worker 10303 exited with status 1
07-18 22:21:34.163 10236 10236 D BreventLoader: signal arrived, update: 0
07-18 22:21:34.164 10226 10226 D BreventLoader: worker 10236 exited with status 0
--- brevent end ---
cannot listen port, please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by Luwattz** [comment]
更新最新版再操作一遍就好了。。。
