### ISSUE TITLE
以root方式启动出现错误

### ISSUE THREAD

**Issue by OldFanta** [brevent/Brevent#140]
已开启开发者模式，且有稳定root权限，出现错误。具体log如下，希望Brevent大大能为我分析一下，万分感谢。手机编辑，难免排版不好，望见谅。

samsung/hero2qltezc/hero2qltechn:7.0/NRD90M/G9550ZCU1AQF7:user/release-keys

```
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:586)
	at java.net.Socket.connect(Socket.java:535)
	at java.net.Socket.<init>(Socket.java:427)
	at java.net.Socket.<init>(Socket.java:243)
	at me.piebridge.brevent.ui.ad.<init>(SimpleAdb.java:59)
	at me.piebridge.brevent.ui.BreventIntentService.b(BreventIntentService.java:200)
	at me.piebridge.brevent.ui.BreventIntentService.c(BreventIntentService.java:172)
	at me.piebridge.brevent.ui.BreventIntentService.a(BreventIntentService.java:106)
	at me.piebridge.brevent.ui.BreventIntentService.onHandleIntent(BreventIntentService.java:91)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java)
```

WARNING: run as root is experimental!!!
checking for server.fail
[command] pm path me.piebridge.brevent
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '10-12 14:30:53.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '10-12 14:30:53.000' -d -s BreventLoader BreventServer
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
换个 su，在你机器上无解。
