### ISSUE TITLE
Server can't start as root

### ISSUE THREAD

**Issue by J316** [brevent/Brevent#141]
google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys

```
java.net.SocketException: Permission denied
	at java.net.Socket.createImpl(Socket.java:473)
	at java.net.Socket.<init>(Socket.java:427)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:292)
	at java.net.Socket.<init>(<Xposed>)
	at java.net.Socket.<init>(Socket.java:241)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:292)
	at java.net.Socket.<init>(<Xposed>)
	at me.piebridge.brevent.ui.ad.<init>(SimpleAdb.java:59)
	at me.piebridge.brevent.ui.BreventIntentService.b(BreventIntentService.java:200)
	at me.piebridge.brevent.ui.BreventIntentService.c(BreventIntentService.java:172)
	at me.piebridge.brevent.ui.BreventIntentService.a(BreventIntentService.java:106)
	at me.piebridge.brevent.ui.BreventIntentService.onHandleIntent(BreventIntentService.java:91)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

WARNING: run as root is experimental!!!
checking for server....started, pid: 9716
checking for stable...........timeout

if you find any issues, please report bug to https://github.com/brevent/Brevent/issues with log
for crash log: logcat -b crash -d
for brevent log: logcat -b main -d -s BreventLoader BreventServer

IMPORTANT: I don't know why it reports Android 6.0.1 as I was already on 7.1.2 the first time I installed this application, and I wiped before and after flashing the new ROM.

**Comment by liudongmiao** [comment]
Check with your ROM provider.

**Comment by liudongmiao** [comment]
Please note, Brevent requires network, at least local network.
Don't be stupid to restrict it's network, then tell me it doesn't work!

**Comment by J316** [comment]
@liudongmiao
To begin, I wish to thank you for being rude and calling me stupid, you are very polite and educated /s
Also, if I'm being called "stupid" for submitting a log of an app to its developer, how would ROM providers call me for submitting to them a log of a random app they have nothing to do with?

About the app, I disabled Xposed and the error changed, asking for local network, as you said, but nothing is restricted, the app has full network access.

**Comment by liudongmiao** [comment]
From the log:

```
java.net.SocketException: Permission denied
```

If you didn't restrict it's network, it won't be anything like permission denied.

And again, run as root is experimental, root has no higher permission than shell.
