### ISSUE TITLE
please report bug to https://github.com/brevent/Brevent/issues with log above

### ISSUE THREAD

**Issue by YummyELine** [brevent/Brevent#168]
WARNING: run as root is experimental!!!
checking for server...started, pid: 19395
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
--- crash start ---
>>> logcat -b crash -t '08-03 09:22:35.000' -d
--- crash end ---
--- brevent start ---
>>> logcat -b main -t '08-03 09:22:35.000' -d -s BreventLoader BreventServer
08-03 09:22:35.734 19373 19373 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
08-03 09:22:36.397 19395 19395 D BreventServer: get service: package
08-03 09:22:36.398 19395 19395 D BreventServer: args: [10]
08-03 09:22:36.398 19395 19395 I BreventServer: signal: 10
08-03 09:22:36.429 19395 19395 I BreventServer: starting Brevent Server 2.0.7a
08-03 09:22:36.441 19395 19395 D BreventServer: get service: package
08-03 09:22:36.442 19395 19395 W BreventServer: version unmatched, running: 2.0.7a, installed: 2.0.7a-ce
08-03 09:22:36.443 19395 19395 I BreventServer: brevent user: 0, uid: 0
08-03 09:22:36.444 19395 19395 I BreventServer: brevent data directory: /data/user/0/com.android.shell
08-03 09:22:36.503 19395 19395 I BreventServer: loading brevent list
08-03 09:22:36.504 19395 19395 I BreventServer: loading brevent conf
08-03 09:22:36.507 19395 19395 D BreventServer: get service: appwidget
08-03 09:22:36.515 19395 19395 D BreventServer: get service: usagestats
08-03 09:22:37.059 19395 19395 D BreventServer: check and brevent
08-03 09:22:37.059 19395 19417 I BreventServer: Brevent Event, now: 1501723357
08-03 09:22:37.060 19395 19395 D BreventServer: get service: notification
08-03 09:22:37.070 19395 19417 I BreventServer: system_server: 3156, now: 1501723357
08-03 09:22:37.196 19395 19395 D BreventServer: get service: activity
08-03 09:22:37.202 19395 19395 D BreventServer: get service: alarm
08-03 09:22:37.203 19395 19395 D BreventServer: get service: wallpaper
08-03 09:22:37.207 19395 19395 E BreventServer: Can't start Brevent:  is not a constant in android.text.Layout$Alignment
08-03 09:22:37.207 19395 19395 E BreventServer: java.lang.IllegalArgumentException:  is not a constant in android.text.Layout$Alignment
08-03 09:22:37.207 19395 19395 E BreventServer:         at java.lang.Enum.valueOf(Enum.java:200)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.text.Layout$Alignment.valueOf(Layout.java:2017)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.text.style.AlignmentSpan$Standard.<init>(AlignmentSpan.java:33)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:711)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.text.TextUtils$1.createFromParcel(TextUtils.java:684)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java:938)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:963)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java:804)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:955)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java:953)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.os.Parcel.createTypedArrayList(Parcel.java:2007)
08-03 09:22:37.207 19395 19395 E BreventServer:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java:3459)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.override.HideApiOverrideM.getRecentTasks(HideApiOverrideM.java:22)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.server.BreventServer.n(BreventServer.java:1267)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:759)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:2065)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2171)
08-03 09:22:37.207 19395 19395 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
08-03 09:22:37.207 19395 19395 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2265)
08-03 09:22:37.207 19395 19395 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-03 09:22:37.207 19395 19395 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
08-03 09:22:37.223 19373 19373 E BreventLoader: worker 19395 exited with status 1
08-03 09:22:37.223 19373 19373 D BreventLoader: signal arrived, update: 0
08-03 09:22:37.224 19354 19354 D BreventLoader: worker 19373 exited with status 0
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
1. 试图使用普通模式，查看问题是否存在。

2. 如果也存在，我再修；否则，自己查看 selinux 之类的。
