### ISSUE TITLE
no recent tasks on some miui rom

### ISSUE THREAD

**Issue by mawanglin** [brevent/Brevent#21]
Brevent Version：v2.1.2
Android Version：v6.0.1（MIUI8）

Error log：
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
checking for server...started, pid: 5508
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
>>> /system/bin/logcat -b crash -t '08-11 23:26:20.000' -d
Unable to open log device 'crash'
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '08-11 23:26:20.000' -d -s BreventLoader BreventServer
08-11 23:26:21.355  5492  5492 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
08-11 23:26:22.145  5508  5508 D BreventServer: get service: package
08-11 23:26:22.155  5508  5508 D BreventServer: args: [10]
08-11 23:26:22.155  5508  5508 I BreventServer: signal: 10
08-11 23:26:22.175  5508  5508 I BreventServer: starting Brevent Server 2.1.2
08-11 23:26:22.185  5508  5508 D BreventServer: get service: package
08-11 23:26:22.195  5508  5508 I BreventServer: brevent user: 0, uid: 2000
08-11 23:26:22.205  5508  5508 I BreventServer: brevent data directory: /data/user/0/com.android.shell
08-11 23:26:22.305  5508  5508 I BreventServer: loading brevent list
08-11 23:26:22.305  5508  5508 I BreventServer: loading brevent conf
08-11 23:26:22.315  5508  5508 D BreventServer: get service: appwidget
08-11 23:26:22.335  5508  5508 D BreventServer: get service: usagestats
08-11 23:26:22.675  5508  5544 I BreventServer: Brevent Event, now: 1502465182
08-11 23:26:22.675  5508  5508 D BreventServer: check and brevent
08-11 23:26:22.685  5508  5508 D BreventServer: get service: notification
08-11 23:26:22.695  5508  5544 I BreventServer: system_server: 1498, now: 1502465182
08-11 23:26:22.795  5508  5508 I BreventServer: remove notification flag 98 for com.miui.home
08-11 23:26:22.795  5508  5508 I BreventServer: remove notification flag 98 for com.miui.securitycenter
08-11 23:26:22.795  5508  5508 I BreventServer: remove notification flag 98 for com.android.providers.contacts
08-11 23:26:22.805  5508  5508 D BreventServer: get service: activity
08-11 23:26:22.855  5508  5508 D BreventServer: get service: alarm
08-11 23:26:22.855  5508  5508 D BreventServer: get service: wallpaper
08-11 23:26:22.875  5508  5508 E BreventServer: Can't start Brevent: bogus span encoding -1
08-11 23:26:22.875  5508  5508 E BreventServer: java.lang.RuntimeException: bogus span encoding -1
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.text.TextUtils$1.createFromParcel(TextUtils.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.text.TextUtils$1.createFromParcel(TextUtils.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.readFromParcel(ActivityManager.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo.<init>(ActivityManager.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManager$RecentTaskInfo$1.createFromParcel(ActivityManager.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.os.Parcel.createTypedArrayList(Parcel.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at android.app.ActivityManagerProxy.getRecentTasks(ActivityManagerNative.java)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.override.HideApiOverrideM.getRecentTasks(HideApiOverrideM.java:22)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.server.BreventServer.n(BreventServer.java:1283)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:775)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:2101)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2218)
08-11 23:26:22.875  5508  5508 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
08-11 23:26:22.875  5508  5508 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2316)
08-11 23:26:22.875  5508  5508 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-11 23:26:22.875  5508  5508 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java)
08-11 23:26:22.945  5492  5492 E BreventLoader: worker 5508 exited with status 1
08-11 23:26:22.945  5492  5492 D BreventLoader: signal arrived, update: 0
08-11 23:26:22.945  5476  5476 D BreventLoader: worker 5492 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
#16

**Comment by liudongmiao** [comment]
感谢反馈，更新了提示。请前往下载最新测试版：piebridge.me/br/next

最终还是不支持。此外，你这个不是官方的 ROM 吧？
