### ISSUE TITLE
root启动服务失败

### ISSUE THREAD

**Issue by wzq98115** [brevent/Brevent#239]
Xiaomi/sagit/sagit:7.1.1/NMF26X/V9.0.3.0.NCACNEI:user/release-keys

WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
WARNING: run as root is experimental!!!
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-31 13:30:50.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-31 13:30:50.000' -d -s BreventLoader BreventServer
01-31 13:30:51.150  9638  9638 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
01-31 13:30:51.170  9638  9638 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
01-31 13:30:51.171  9657  9657 D BreventLoader: start: 1517376650
01-31 13:30:51.583  9657  9657 I BreventServer: args: [10, me.piebridge.brevent, 1517376650]
01-31 13:30:51.598  9657  9657 I BreventServer: server log name: server.20180131.1330.9657.txt
01-31 13:30:51.600  9657  9657 I BreventServer: starting Brevent Server 2.6.6
01-31 13:30:51.633  9657  9657 I BreventServer: brevent user: 0, uid: 0
01-31 13:30:51.634  9657  9657 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
01-31 13:30:51.654  9657  9657 I BreventServer: no service overlay
01-31 13:30:51.662  9657  9657 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 119
01-31 13:30:51.713  9657  9657 E BreventServer: Can't dump appwidget(brevent dumpsys dead)
01-31 13:30:51.713  9657  9657 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
01-31 13:30:51.713  9657  9657 E BreventServer: 	at android.os.BinderProxy.transactNative(Native Method)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at android.os.BinderProxy.transact(Binder.java:618)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at android.os.BinderProxy.dumpAsync(Binder.java:654)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.h.b(HideApi.java:898)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:885)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:880)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:339)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.d.<init>(BreventServerImpl.java:351)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.d.a(BreventServerImpl.java:2754)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:33)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:142)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
01-31 13:30:51.713  9657  9657 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
01-31 13:30:51.713  9657  9657 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/17
01-31 13:30:51.741  9638  9638 E BreventLoader: worker 9657 exited with status 1
01-31 13:30:51.741  9638  9638 D BreventLoader: signal arrived, update: 0
01-31 13:30:51.742  9634  9634 D BreventLoader: worker 9638 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
WARNING: linker: /data/local/tmp/brevent: unsupported flags DT_FLAGS_1=0x8000001
WARNING: run as root is experimental!!!
checking for server..started, pid: 9698
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '01-31 13:30:52.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '01-31 13:30:52.000' -d -s BreventLoader BreventServer
01-31 13:30:52.780  9686  9686 D BreventLoader: line: package:/data/app/me.piebridge.brevent-1/base.apk
01-31 13:30:52.800  9686  9686 D BreventLoader: loader path: /data/app/me.piebridge.brevent-1/base.apk
01-31 13:30:52.801  9698  9698 D BreventLoader: start: 1517376652
01-31 13:30:53.221  9698  9698 I BreventServer: args: [10, me.piebridge.brevent, 1517376652]
01-31 13:30:53.253  9698  9698 I BreventServer: server log name: server.20180131.1330.9698.txt
01-31 13:30:53.255  9698  9698 I BreventServer: starting Brevent Server 2.6.6
01-31 13:30:53.285  9698  9698 I BreventServer: brevent user: 0, uid: 0
01-31 13:30:53.286  9698  9698 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
01-31 13:30:53.301  9698  9698 I BreventServer: no service overlay
01-31 13:30:53.307  9698  9698 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 119
01-31 13:30:53.461  9698  9698 E BreventServer: Can't dump appwidget(brevent dumpsys dead)
01-31 13:30:53.461  9698  9698 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
01-31 13:30:53.461  9698  9698 E BreventServer: 	at android.os.BinderProxy.transactNative(Native Method)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at android.os.BinderProxy.transact(Binder.java:618)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at android.os.BinderProxy.dumpAsync(Binder.java:654)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.h.b(HideApi.java:898)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:885)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:880)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.h.a(HideApi.java:339)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.d.<init>(BreventServerImpl.java:351)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.d.a(BreventServerImpl.java:2754)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:33)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:142)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
01-31 13:30:53.461  9698  9698 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
01-31 13:30:53.461  9698  9698 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/17
01-31 13:30:53.482  9686  9686 E BreventLoader: worker 9698 exited with status 1
01-31 13:30:53.482  9686  9686 D BreventLoader: signal arrived, update: 0
01-31 13:30:53.483  9682  9682 D BreventLoader: worker 9686 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by vvb2060** [comment]
#17
