### ISSUE TITLE
透过Magisk取得root权限后无法启用黑域的root模式

### ISSUE THREAD

**Issue by FengkuiChan** [brevent/Brevent#26]
motorola/shamu_retcn/shamu_t:5.0.2/LXG22.67-7.1/2:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server..started, pid: 9284
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-2/base.apk
[command] logcat -b crash -t '08-16 13:32:59.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-16 13:32:59.000' -d -s BreventLoader BreventServer
D/BreventLoader( 9233): line: package:/data/app/me.piebridge.brevent-2/base.apk
D/BreventLoader( 9233): 
D/BreventLoader( 9233): loader path: /data/app/me.piebridge.brevent-2/base.apk
D/BreventServer( 9284): get service: package
D/BreventServer( 9284): args: [10]
I/BreventServer( 9284): signal: 10
I/BreventServer( 9284): starting Brevent Server 2.1.3
D/BreventServer( 9284): get service: package
I/BreventServer( 9284): brevent user: 0, uid: 0
I/BreventServer( 9284): brevent data directory: /data/data/com.android.shell
I/BreventServer( 9284): loading brevent list
I/BreventServer( 9284): load /data/data/com.android.shell/me.piebridge.brevent.list, size: 86
I/BreventServer( 9284): loading brevent conf
D/BreventServer( 9284): get service: appwidget
W/BreventServer( 9284): Cannot dump appwidget []
D/BreventServer( 9284): Can't dump widgets (ignore)
I/BreventServer( 9284): Brevent Event, now: 1502861580
D/BreventServer( 9284): check and brevent
D/BreventServer( 9284): get service: notification
W/BreventServer( 9284): Cannot dump notification []
W/BreventServer( 9284): Can't dump notifications
W/BreventServer( 9284): Cannot dump appwidget []
D/BreventServer( 9284): Can't dump widgets (ignore)
D/BreventServer( 9284): get service: activity
W/BreventServer( 9284): Cannot dump activity [activities]
E/BreventServer( 9284): Can't dump activities
E/BreventServer( 9284): java.io.IOException: android.os.TransactionTooLargeException
E/BreventServer( 9284): 	at me.piebridge.brevent.server.e.b(HideApi.java:861)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.e.a(HideApi.java:828)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.e.a(HideApi.java:823)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.e.c(HideApi.java:307)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.BreventServer.B(BreventServer.java:2014)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.BreventServer.j(BreventServer.java:798)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.BreventServer.i(BreventServer.java:2187)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2311)
E/BreventServer( 9284): 	at java.lang.reflect.Method.invoke(Native Method)
E/BreventServer( 9284): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2413)
E/BreventServer( 9284): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/BreventServer( 9284): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
E/BreventServer( 9284): Caused by: android.os.TransactionTooLargeException
E/BreventServer( 9284): 	at android.os.BinderProxy.transactNative(Native Method)
E/BreventServer( 9284): 	at android.os.BinderProxy.transact(Binder.java:496)
E/BreventServer( 9284): 	at android.os.BinderProxy.dumpAsync(Binder.java:526)
E/BreventServer( 9284): 	at me.piebridge.brevent.server.e.b(HideApi.java:843)
E/BreventServer( 9284): 	... 12 more
I/BreventServer( 9284): system_server: 1121, now: 1502861580
E/BreventLoader( 9233): worker 9284 exited with status 1
D/BreventLoader( 9233): signal arrived, update: 0
D/BreventLoader( 9229): worker 9233 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liyufan** [comment]
参考#17

**Comment by liudongmiao** [comment]
@FengkuiChan 你执行以下命令看下：

```
dumpsys activity activities
```
