### ISSUE TITLE
误杀无障碍服务

### ISSUE THREAD

**Issue by gavinweixin** [brevent/Brevent#273]
手势软件Gesture Control需要用到无障碍服务，虽然软件加入了黑域白名单，但是无障碍服务会被误杀。具体表现在使用软件一段时间后，软件提示已自动停止，然后发现该软件的无障碍服务已被关闭。

**Comment by jr21066** [comment]
加入自启动后应该就好了，我是miui

**Comment by gavinweixin** [comment]
系统是PureNexus 7.1.1

**Comment by vvb2060** [comment]
黑域没有白名单，黑域是直接不处理黑域清单外应用。并且不允许黑域无障碍应用，已被黑域的会弹窗提示取消。

**Comment by gavinweixin** [comment]
sorry，我的表达有误。
但这个现象是上一个版本才开始出现的（现在是2.9.7，Play Store Beta计划），之前没有这个问题。

**Comment by vvb2060** [comment]
如果认为黑域有异常行为，请提供日志：点按黑域菜单内日志按钮。还有相关应用包名：在应用弹出菜单中点按 复制包名 选项。

**Comment by gavinweixin** [comment]
链接: pan.baidu.com/s/1RGy6_A84f7t_V-8a_ORCYg 密码: 929e
包名：com.ss.edgegestures

**Comment by liudongmiao** [comment]
```
03-10 18:31:06.779  5198  5546 E AndroidRuntime: FATAL EXCEPTION: Thread-2
03-10 18:31:06.779  5198  5546 E AndroidRuntime: Process: com.ss.edgegestures, PID: 5198
03-10 18:31:06.779  5198  5546 E AndroidRuntime: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.os.Handler.<init>(Handler.java:200)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.os.Handler.<init>(Handler.java:114)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.widget.Toast$TN$2.<init>(Toast.java:340)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.widget.Toast$TN.<init>(Toast.java:340)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.widget.Toast.<init>(Toast.java:107)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.widget.Toast.makeText(Toast.java:260)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at android.widget.Toast.makeText(Toast.java:287)
03-10 18:31:06.779  5198  5546 E AndroidRuntime:        at com.ss.edgegestures.EdgeView$2.run(EdgeView.java:591)
```
这个应用大量出现自己 crash，与黑域无关。
如果你认为安装黑域就导致这个情况，我本人建议直接卸载黑域。
黑域仅处理黑域清单内应用，强行停止其它应用有完整日志。
同时，黑域从不保证与系统及其它应用兼容性，只能保证黑域从不破坏其它应用完整性。
此外，使用黑域，除非使用了 应用操作，否则，出现“应用停止” 或者  crash 与黑域无关。

**Comment by gavinweixin** [comment]
好的，谢谢
