### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter 

### ISSUE THREAD

**Issue by liyufan** [brevent/Brevent#29]
提示启动黑域服务，启动黑域服务后突然闪退
无法重现
FATAL EXCEPTION: main
 Process: me.piebridge.brevent, PID: 27309
 java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{acfac86 position=14 id=-1, oldPos=-1, pLpos:-1 no parent}
 	at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5297)
 	at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5479)
 	at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5440)
 	at android.support.v7.widget.RecyclerView$o.c(RecyclerView.java:5436)
 	at android.support.v7.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:2224)
 	at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1551)
 	at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1511)
 	at android.support.v7.widget.LinearLayoutManager.c(LinearLayoutManager.java:1325)
 	at android.support.v7.widget.LinearLayoutManager.b(LinearLayoutManager.java:1061)
 	at android.support.v7.widget.RecyclerView$v.run(RecyclerView.java:4726)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
 	at android.view.Choreographer.doFrame(Choreographer.java:618)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
 	at android.os.Handler.handleCallback(Handler.java:751)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:154)
 	at android.app.ActivityThread.main(ActivityThread.java:6322)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by liudongmiao** [comment]
我最近也看到好多类似的反馈，完全不知道怎么发生的。

**Comment by liudongmiao** [comment]
@liyufan 我根据这个异常，尝试做了下修复：https://piebridge.me/br/next/
你帮忙测试下，看接下来一段时间，是否有崩溃情况。

由于以上情况很难重现，从代码角度讲，多出现在安装/卸载/状态变更等情况。
目前我做了特殊处理，理论上，应该已经解决问题。但有待校验。

**Comment by liyufan** [comment]
试了几天，没发现闪退问题，应该是已经修复了
