### ISSUE TITLE
Xperia z ultra c6833 brevent fail to start server in root mode log

### ISSUE THREAD

**Issue by N-egaran** [brevent/Brevent#31]
Sony/C6833/C6833:5.1.1/14.6.A.1.236/834130922:user/release-keys
SELinux: true

WARNING: run as root is experimental!!!
checking for server...started, pid: 26310
checking for stable..quited

please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
[command] logcat -b crash -t '08-18 17:12:19.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-18 17:12:19.000' -d -s BreventLoader BreventServer
D/BreventLoader(26257): line: package:/data/app/me.piebridge.brevent-1/base.apk
D/BreventLoader(26257): 
D/BreventLoader(26257): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventServer(26310): get service: package
D/BreventServer(26310): args: [10]
I/BreventServer(26310): signal: 10
I/BreventServer(26310): starting Brevent Server 2.1.3
D/BreventServer(26310): get service: package
I/BreventServer(26310): brevent user: 0, uid: 0
I/BreventServer(26310): brevent data directory: /data/data/com.android.shell
I/BreventServer(26310): loading brevent list
I/BreventServer(26310): loading brevent conf
D/BreventServer(26310): get service: appwidget
D/BreventServer(26310): check and brevent
D/BreventServer(26310): get service: notification
I/BreventServer(26310): Brevent Event, now: 1503060141
I/BreventServer(26310): system_server: 950, now: 1503060141
D/BreventServer(26310): get service: activity
D/BreventServer(26310): get service: alarm
D/BreventServer(26310): get service: wallpaper
D/BreventServer(26310): check again in 3600s
D/BreventServer(26310): check and brevent, took 334ms
I/BreventServer(26310): notification_cancel_all events: 2
D/BreventServer(26310): get service: power
I/BreventServer(26310): charging: true
I/BreventServer(26310): support standby: false
I/BreventServer(26310): support stopped: true
I/BreventServer(26310): support upgrade: true
I/BreventServer(26310): Brevent Server 2.1.3 started
D/BreventServer(26310): get service: appops
D/BreventServer(26310): set appops, package: me.piebridge.brevent, package uid: 10295, code: 43, mode: 0
I/BreventServer(26310): granted permission
I/BreventServer(26310): checking port
E/BreventServer(26310): Cannot connect to server (brevent network error)
E/BreventServer(26310): java.net.ConnectException: failed to connect to localhost/::1 (port 59526): connect failed: EBADF (Bad file number)
E/BreventServer(26310): 	at libcore.io.IoBridge.connect(IoBridge.java:128)
E/BreventServer(26310): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
E/BreventServer(26310): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:163)
E/BreventServer(26310): 	at java.net.Socket.startupSocket(Socket.java:595)
E/BreventServer(26310): 	at java.net.Socket.<init>(Socket.java:231)
E/BreventServer(26310): 	at me.piebridge.brevent.protocol.BreventProtocol.checkPortSync(BreventProtocol.java:203)
E/BreventServer(26310): 	at me.piebridge.brevent.server.BreventServer$1.run(BreventServer.java:2254)
E/BreventServer(26310): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/BreventServer(26310): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/BreventServer(26310): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
E/BreventServer(26310): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
E/BreventServer(26310): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/BreventServer(26310): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/BreventServer(26310): 	at java.lang.Thread.run(Thread.java:818)
E/BreventServer(26310): Caused by: android.system.ErrnoException: connect failed: EBADF (Bad file number)
E/BreventServer(26310): 	at libcore.io.Posix.connect(Native Method)
E/BreventServer(26310): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
E/BreventServer(26310): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:141)
E/BreventServer(26310): 	at libcore.io.IoBridge.connect(IoBridge.java:126)
E/BreventServer(26310): 	... 13 more
E/BreventLoader(26257): worker 26310 exited with status 1
D/BreventLoader(26257): signal arrived, update: 0
D/BreventLoader(26253): worker 26257 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
please disable selinux, or switch to another su.

**Comment by N-egaran** [comment]
thanks for the answer but how do I disable selinux in stock ROM ?

**Comment by vvb2060** [comment]
@bmnmji 
`adb shell su -c setenforce 0`

**Comment by N-egaran** [comment]
thanks
