### ISSUE TITLE
360N5 adb命令crash

### ISSUE THREAD

**Issue by NickLiu635** [brevent/Brevent#320]
```
--- crash start ---
[command] logcat -b crash -t '04-22 13:49:43.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '04-22 13:49:43.000' -d -s BreventLoader BreventServer
04-22 13:49:44.839 11011 11011 E BreventServer: Can't start Brevent: Attempt to read from field 'boolean android.content.pm.PackageInfo.coreApp' on a null object reference
04-22 13:49:44.839 11011 11011 E BreventServer: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.PackageInfo.coreApp' on a null object reference
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.override.HideApiOverride.isCoreApp(HideApiOverride.java:441)
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.server.c.a(BreventServerImpl.java:672)
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.server.c.<init>(BreventServerImpl.java:428)
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.server.c.a(BreventServerImpl.java:4131)
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:27)
04-22 13:49:44.839 11011 11011 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
04-22 13:49:44.839 11011 11011 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:63)
04-22 13:49:44.839 11011 11011 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-22 13:49:44.839 11011 11011 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:265)
04-22 13:49:44.859 11001 11001 E BreventLoader: worker 11011 exited with status 3
04-22 13:49:44.861 10995 10995 I BreventLoader: worker 11001 exited with status 0
--- brevent end ---
```

**Comment by NickLiu635** [comment]
360N5 V132稳定版  Android 6.0.1 ，3.10.84-pref

**Comment by NickLiu635** [comment]
WARNING: brevent on Android 5.X - 6.0 is experimental!!!
checking for server..started, pid: 16923
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-1/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below

**Comment by yeshang127** [comment]
一样，版本一样。。错误也一样..

**Comment by liudongmiao** [comment]
如果获取系统全部包名，然后获取应用信息也能空指针。。。。
等下个版本吧。
