### ISSUE TITLE
Android p 黑域主界面点击app名 crash

### ISSUE THREAD

**Issue by mingmxren** [brevent/Brevent#343]
Android p 黑域点击主界面点击app名直接crash

```
05-11 23:45:21.035 26754 26754 E AndroidRuntime: FATAL EXCEPTION: main
05-11 23:45:21.035 26754 26754 E AndroidRuntime: Process: me.piebridge.brevent, PID: 26754
05-11 23:45:21.035 26754 26754 E AndroidRuntime: java.lang.NoSuchMethodError: No static method opToSwitch(I)I in class Landroid/app/AppOpsManager; or its super classes (declaration of 'android.app.AppOpsManager' appears in /system/framework/framework.jar)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.a.a.i(HideApiOverride.java:151)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.ui.ad.<clinit>(OpsItemAdapter.java:57)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.ui.ad.a(OpsItemAdapter.java:428)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.ui.BreventActivity.z(BreventActivity.java:2549)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.ui.p.onCreateContextMenu(AppsItemViewHolder.java:93)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View.createContextMenu(View.java:13336)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at com.android.internal.view.menu.ContextMenuBuilder.showDialog(ContextMenuBuilder.java:81)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at com.android.internal.policy.DecorView.showContextMenuForChildInternal(DecorView.java:823)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at com.android.internal.policy.DecorView.showContextMenuForChild(DecorView.java:793)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.ViewGroup.showContextMenuForChild(ViewGroup.java:928)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View.showContextMenu(View.java:6752)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at me.piebridge.brevent.ui.n.onClick(AppsItemAdapter.java:308)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View.performClick(View.java:6597)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:6574)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View.access$3100(View.java:778)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:25881)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6656)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-11 23:45:21.035 26754 26754 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

**Comment by vvb2060** [comment]
升级到[beta版](https://jianyu.io/br/beta/)
