### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by beginor** [brevent/Brevent#414]
```sh
adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
```

checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '08-13 10:53:03.000' -d
08-13 10:53:03.984 15070 15070 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
08-13 10:53:03.984 15070 15070 E AndroidRuntime: java.lang.reflect.InvocationTargetException
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:62)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:289)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/lib/arm64/libreader.so"
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1657)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.LogReader.<clinit>(Unknown Source:12)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.LogReader.version(Native Method)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.brevent.server.cON.<init>(Unknown Source:387)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.brevent.server.cON.do(Unknown Source:4304)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:26)
08-13 10:53:03.984 15070 15070 E AndroidRuntime: 	... 4 more
08-13 10:53:03.985 15070 15070 E AndroidRuntime: Error reporting crash
08-13 10:53:03.985 15070 15070 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:764)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:56)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4232)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4230)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4225)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:116)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
08-13 10:53:03.985 15070 15070 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-13 10:53:03.000' -d -s BreventLoader BreventServer
08-13 10:53:03.035 15059 15059 I BreventLoader: pm path me.piebridge.brevent
08-13 10:53:03.448 15059 15059 I BreventLoader: line: package:/data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/base.apk
08-13 10:53:03.470 15059 15059 I BreventLoader: loader path: /data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/base.apk
08-13 10:53:03.474 15070 15070 I BreventLoader: start: 1534128783
08-13 10:53:03.878 15070 15070 I BreventServer: args: [10, me.piebridge.brevent, 1534128783]
08-13 10:53:03.936 15070 15070 I BreventServer: server log name: server.20180813.1053.15070.txt
08-13 10:53:03.939 15070 15070 I BreventServer: starting Brevent Server 3.3.9.1
08-13 10:53:03.969 15070 15070 I BreventServer: brevent version: 3.3.9.1
08-13 10:53:03.982 15070 15070 E BreventServer: dex2oat-cmdline: --instruction-set=arm64 --instruction-set-features=a53 --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m --instruction-set-variant=kryo --instruction-set-features=default --dex-file=/data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/base.apk --output-vdex-fd=9 --oat-fd=10 --oat-location=/data/app/me.piebridge.brevent-rU5cyFFHrStKLkWgpTollA==/oat/arm64/base.odex --compiler-filter=quicken --class-loader-context=&
08-13 10:53:03.998 15059 15059 E BreventLoader: worker 15070 exited on signal 9
08-13 10:53:03.998 15059 15059 I BreventLoader: signal arrived, update: 0
08-13 10:53:03.999 15054 15054 I BreventLoader: worker 15059 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by beginor** [comment]
应该是不小心改动了 usb 模式， 删除重装之后问题解决

**Comment by liudongmiao** [comment]
并不是，你机器触发了黑阈反修改检测。
如果是官方 ROM，且没有应用任何主题，请继续回复。

**Comment by beginor** [comment]
设备是 Z2 Pro (z2_row) ， 系统是 [AospExtended v5.8](https://downloads.aospextended.com/z2_row/) ， 不官方的 ZUI 。 

个人没有做过任何修改， 也没有安装什么主题， 印象中是为了复制文件到手机改动过 USB 模式。
