### ISSUE TITLE
nexus 6p Andriod 8.1.0

### ISSUE THREAD

**Issue by sixdian** [brevent/Brevent#416]
<details>
<summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '08-14 21:50:45.000' -d
08-14 21:50:51.646 13658 13674 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: DumpPipe
08-14 21:50:51.646 13658 13674 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 127MB until OOM, max allowed footprint 92530984, growth limit 201326592
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at java.util.Arrays.copyOf(Arrays.java:3164)
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at me.piebridge.brevent.server.AUx.run(Unknown Source:111)
08-14 21:50:51.646 13658 13674 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-14 21:50:45.000' -d -s BreventLoader BreventServer
08-14 21:50:45.523 13640 13640 I BreventLoader: sdk: 27
08-14 21:50:45.560 13646 13646 I BreventLoader: pm path me.piebridge.brevent
08-14 21:50:46.185 13646 13646 I BreventLoader: line: package:/data/app/me.piebridge.brevent-MnRX1eVIadBvWrL_AdWVNQ==/base.apk
08-14 21:50:46.205 13646 13646 I BreventLoader: loader path: /data/app/me.piebridge.brevent-MnRX1eVIadBvWrL_AdWVNQ==/base.apk
08-14 21:50:46.207 13658 13658 I BreventLoader: start: 1534254645
08-14 21:50:46.613 13658 13658 I BreventServer: args: [10, me.piebridge.brevent, 1534254645]
08-14 21:50:46.799 13658 13658 I BreventServer: server log name: server.20180814.2150.13658.txt
08-14 21:50:46.799 13658 13658 I BreventServer: starting Brevent Server 3.3.9.1
08-14 21:50:46.877 13658 13658 I BreventServer: brevent version: 3.3.9.1
08-14 21:50:46.915 13658 13658 I BreventServer: brevent user: 0, uid: 2000
08-14 21:50:47.038 13658 13658 I BreventServer: core apps: [com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.android.mms.service, com.android.defcontainer, android, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.inputdevices, com.google.android.dialer, com.android.server.telecom, com.google.android.packageinstaller, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.qualcomm.atfwd, com.google.android.inputmethod.latin]
08-14 21:50:47.039 13658 13658 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, android, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
08-14 21:50:47.044 13658 13658 I BreventServer: installer: com.google.android.packageinstaller
08-14 21:50:47.045 13658 13658 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-14 21:50:47.066 13658 13658 I BreventServer: fcm packages: {com.nextcloud.client, com.github.shadowsocks, com.google.android.youtube, com.google.android.googlequicksearchbox, org.telegram.messenger, com.google.android.apps.enterprise.dmagent, com.alphainventor.filemanager, com.google.android.apps.messaging, com.google.android.apps.currents, com.google.android.apps.genie.geniewidget, com.android.vending, com.tencent.mm, com.digibites.accubattery, com.coffeebeanventures.easyvoicerecorder, com.google.android.music, com.google.android.dialer, com.google.android.apps.nbu.files, com.mxtech.videoplayer.ad, com.google.android.apps.docs, com.google.android.apps.maps, com.google.android.apps.plus, com.airvisual, com.google.android.contacts, com.android.chrome, com.google.android.street, com.google.android.gms, com.google.android.gsf, com.google.android.apps.walletnfcrel, com.google.android.videos, io.lingvist.android, com.google.android.apps.photos, ren.growth, com.google.android.calendar, com.sonelli.juicessh, com.google.android.backuptransport, com.strava, com.google.android.apps.books, com.google.android.apps.tycho, com.taobao.idlefish, com.accuweather.android, com.google.android.talk, com.videogo, com.taobao.taobao, com.xiaomi.smarthome, com.google.android.apps.gcs, com.ddm.iptools}
08-14 21:50:47.108 13658 13658 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 63
08-14 21:50:47.129 13658 13658 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 53
08-14 21:50:51.709 13646 13646 E BreventLoader: worker 13658 exited on signal 9
08-14 21:50:51.709 13646 13646 I BreventLoader: signal arrived, update: 0
08-14 21:50:52.395 13640 13640 I BreventLoader: worker 13646 exited with status 0
--- brevent end ---
```
</details>

**Comment by liudongmiao** [comment]
If it's stock rom, please try again.
For non-stock rom, won't support.

**Comment by sixdian** [comment]
重试依然无法启动，原生系统，没刷过机。
checking for server...started, pid: 5992
checking for stable...quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-GPeS0hxW4o6f7MfDhgb9MQ==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
<details>
<summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '08-24 12:48:51.000' -d
08-24 12:48:56.647  5992  6022 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: DumpPipe
08-24 12:48:56.647  5992  6022 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 134217744 byte allocation with 25165824 free bytes and 127MB until OOM, max allowed footprint 92514856, growth limit 201326592
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at java.util.Arrays.copyOf(Arrays.java:3164)
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at me.piebridge.brevent.server.AUx.run(Unknown Source:111)
08-24 12:48:56.647  5992  6022 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-24 12:48:51.000' -d -s BreventLoader BreventServer
08-24 12:48:51.420  5950  5950 I BreventLoader: sdk: 27
08-24 12:48:51.492  5956  5956 I BreventLoader: pm path me.piebridge.brevent
08-24 12:48:52.489  5956  5956 I BreventLoader: line: package:/data/app/me.piebridge.brevent-GPeS0hxW4o6f7MfDhgb9MQ==/base.apk
08-24 12:48:52.527  5956  5956 I BreventLoader: loader path: /data/app/me.piebridge.brevent-GPeS0hxW4o6f7MfDhgb9MQ==/base.apk
08-24 12:48:52.529  5992  5992 I BreventLoader: start: 1535086131
08-24 12:48:52.900  5992  5992 I BreventServer: args: [10, me.piebridge.brevent, 1535086131]
08-24 12:48:52.949  5992  5992 I BreventServer: server log name: server.20180824.1248.5992.txt
08-24 12:48:52.950  5992  5992 I BreventServer: starting Brevent Server 3.3.9.1
08-24 12:48:52.986  5992  5992 I BreventServer: brevent version: 3.3.9.1
08-24 12:48:53.012  5992  5992 I BreventServer: brevent user: 0, uid: 2000
08-24 12:48:53.145  5992  5992 I BreventServer: core apps: [com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.android.mms.service, com.android.defcontainer, android, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.inputdevices, com.google.android.dialer, com.android.server.telecom, com.google.android.packageinstaller, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.qualcomm.atfwd, com.google.android.inputmethod.latin]
08-24 12:48:53.146  5992  5992 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, android, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
08-24 12:48:53.150  5992  5992 I BreventServer: installer: com.google.android.packageinstaller
08-24 12:48:53.152  5992  5992 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-24 12:48:53.173  5992  5992 I BreventServer: fcm packages: {com.nextcloud.client, com.github.shadowsocks, com.google.android.youtube, com.oasisfeng.greenify, com.google.android.googlequicksearchbox, org.telegram.messenger, com.google.android.apps.enterprise.dmagent, com.alphainventor.filemanager, com.google.android.apps.messaging, com.google.android.apps.currents, com.google.android.apps.genie.geniewidget, com.android.vending, com.tencent.mm, com.digibites.accubattery, com.coffeebeanventures.easyvoicerecorder, com.google.android.music, com.google.android.dialer, com.google.android.apps.nbu.files, com.mxtech.videoplayer.ad, org.xdty.callerinfo, com.google.android.apps.docs, com.google.android.apps.maps, com.google.android.apps.plus, com.airvisual, com.google.android.contacts, com.android.chrome, com.google.android.street, com.google.android.gms, com.google.android.gsf, com.google.android.apps.walletnfcrel, com.google.android.videos, io.lingvist.android, com.google.android.apps.photos, ren.growth, com.google.android.calendar, com.sonelli.juicessh, com.google.android.backuptransport, com.strava, com.google.android.apps.books, com.google.android.apps.tycho, com.taobao.idlefish, com.accuweather.android, com.google.android.talk, com.videogo, com.taobao.taobao, com.xiaomi.smarthome, com.google.android.apps.gcs, com.ddm.iptools}
08-24 12:48:53.212  5992  5992 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 63
08-24 12:48:53.232  5992  5992 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 53
08-24 12:48:56.673  5956  5956 E BreventLoader: worker 5992 exited on signal 9
08-24 12:48:56.673  5956  5956 I BreventLoader: signal arrived, update: 0
08-24 12:48:56.674  5950  5950 I BreventLoader: worker 5956 exited with status 0
--- brevent end ---
```
</details>
please report bug to https://github.com/brevent/Brevent/issues with log above

**Comment by liudongmiao** [comment]
attach files in /sdcard/Android/data/me.piebridge.brevent/

**Comment by sixdian** [comment]
[me.piebridge.brevent.zip](https://github.com/brevent/Brevent/files/2320254/me.piebridge.brevent.zip)

**Comment by liudongmiao** [comment]
please check latest alpha version: https://jianyu.io/br/alpha/

**Comment by sixdian** [comment]
新版本可以正常开启，谢谢！

**Comment by liudongmiao** [comment]
好的，非常感谢汇报。请发邮件至 brevent@jianyu.io，好赠送您特别贡献兑换码。
