### ISSUE TITLE
请帮忙做一个兼容性处理

### ISSUE THREAD

**Issue by AndyWing** [brevent/Brevent#481]
在motorola新版本系统上面,fw修改了wallpaper manager中的getwallpaper的aidl参数,根据log显示,
brevent不是通过android.app.WallpaperManager去调用这个方法,而是可能通过aidl直接通信wallpapermanagerservice使用的, 所以可能导致了brevent服务一直处于奔溃状态.

moto内部我在推动fw进行一个兼容处理,但是可能周期比较长~~
所以 能不能请你帮忙对这个api的使用做一个调整或者兼容性处理?

谢谢!

adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..started, pid: 12233
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-2tAWdQHx5qUtgmPXVbt0FQ==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '11-26 14:31:45.000' -d
11-26 14:31:46.881 12233 12233 E AndroidRuntime: FATAL EXCEPTION: main
11-26 14:31:46.881 12233 12233 E AndroidRuntime: PID: 12233
11-26 14:31:46.881 12233 12233 E AndroidRuntime: java.lang.reflect.InvocationTargetException
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:64)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method getWallpaperInfo(I)Landroid/app/WallpaperInfo; in class Landroid/app/IWallpaperManager; or its super classes (declaration of 'android.app.IWallpaperManager' appears in /system/framework/framework.jar)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.µμΡ.μΗ(Unknown Source:853)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.CON.Ηµ(Unknown Source:1432)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.CON.handleMessage(Unknown Source:1149)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.CON.dispatchMessage(Unknown Source:1097)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.CON.do(Unknown Source:4450)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:28)
11-26 14:31:46.881 12233 12233 E AndroidRuntime: 	... 4 more
11-26 14:31:46.882 12233 12233 E AndroidRuntime: Error reporting crash
11-26 14:31:46.882 12233 12233 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:1136)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:3648)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
11-26 14:31:46.882 12233 12233 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '11-26 14:31:45.000' -d -s BreventLoader BreventServer
11-26 14:31:45.549 12224 12224 I BreventLoader: sdk: 28
11-26 14:31:45.593 12229 12229 I BreventLoader: pm path me.piebridge.brevent
11-26 14:31:45.653 12229 12229 I BreventLoader: line: package:/data/app/me.piebridge.brevent-2tAWdQHx5qUtgmPXVbt0FQ==/base.apk
11-26 14:31:45.660 12229 12229 I BreventLoader: loader path: /data/app/me.piebridge.brevent-2tAWdQHx5qUtgmPXVbt0FQ==/base.apk
11-26 14:31:45.662 12233 12233 I BreventLoader: start: 1543213905
11-26 14:31:46.050 12233 12233 I BreventServer: args: [10, me.piebridge.brevent, 1543213905]
11-26 14:31:46.097 12233 12233 I BreventServer: server log name: server.20181126.1431.12233.txt
11-26 14:31:46.098 12233 12233 I BreventServer: starting Brevent Server 3.5.4.1
11-26 14:31:46.122 12233 12233 I BreventServer: brevent version: 3.5.4.1
11-26 14:31:46.135 12233 12233 I BreventServer: brevent user: 0, uid: 2000
11-26 14:31:46.205 12233 12233 I BreventServer: core apps: [com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.android.mms.service, com.qualcomm.qti.telephonyservice, com.google.android.vr.inputmethod, com.android.defcontainer, com.android.carrierconfig, android, org.codeaurora.ims, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.motorola.android.providers.settings, com.android.dialer, com.google.android.packageinstaller, com.android.proxyhandler, com.android.service.ims.presence, com.android.settings, com.motorola.InductiveChargeUI, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.google.android.inputmethod.latin]
11-26 14:31:46.206 12233 12233 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, com.android.carrierconfig, android, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.dialer, com.android.proxyhandler, com.android.service.ims.presence, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
11-26 14:31:46.207 12233 12233 I BreventServer: installer: com.google.android.packageinstaller
11-26 14:31:46.207 12233 12233 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
11-26 14:31:46.230 12233 12233 I BreventServer: fcm packages: {com.github.shadowsocks, com.google.android.youtube, com.sony.songpal.mdr, com.google.android.googlequicksearchbox, com.motorola.ccc.devicemanagement, com.google.android.apps.messaging, com.paypal.android.p2pmobile, com.motorola.visualvoicemail, com.motorola.ccc.ota, com.motorola.ccc.notification, com.android.vending, com.tencent.mm, com.google.android.apps.work.oobconfig, com.blizzard.messenger, com.google.android.apps.tachyon, com.google.android.music, com.google.android.apps.docs, com.google.android.apps.maps, com.android.chrome, com.google.android.gms, com.google.android.gsf, com.motorola.genie, com.google.android.videos, com.google.android.apps.photos, com.google.android.calendar, com.motorola.paks, com.motorola.ccc.internal, com.google.android.backuptransport, com.taobao.taobao, com.xiaomi.smarthome, com.Foxit.Mobile.PDF}
11-26 14:31:46.242 12233 12233 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 36
11-26 14:31:46.259 12233 12233 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
11-26 14:31:46.259 12233 12233 I BreventServer: disabling: {}
11-26 14:31:46.260 12233 12233 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 19
11-26 14:31:46.260 12233 12233 I BreventServer: ppid: 12229
11-26 14:31:46.260 12233 12233 I BreventServer: checking standby, sdk: 28
11-26 14:31:46.436 12233 12233 I BreventServer: init widgets
11-26 14:31:46.447 12233 12233 I BreventServer: init notifications
11-26 14:31:46.527 12233 12233 I BreventServer: recentsComponentName: com.motorola.launcher3/com.android.quickstep.RecentsActivity
11-26 14:31:46.528 12233 12233 I BreventServer: recents package name: com.motorola.launcher3
11-26 14:31:46.563 12233 12233 I BreventServer: use com.google.android.ext.shared to check upgrade and disable
11-26 14:31:46.567 12233 12233 I BreventServer: update com.google.android.ext.shared to disabled-user, new state: disabled-user
11-26 14:31:46.570 12233 12233 I BreventServer: update com.google.android.ext.shared to enabled, new state: enabled
11-26 14:31:46.576 12233 12249 I BreventServer: system_server: 1633
11-26 14:31:46.577 12233 12249 I BreventServer: android_log_clockid: 0x7742f99f1c
11-26 14:31:46.577 12233 12249 I BreventServer: clockid: 0, realtime: 0
11-26 14:31:46.577 12233 12249 I BreventServer: system_server: 1633, now: 1543213906
11-26 14:31:46.603 12233 12233 I BreventServer: support standby: true
11-26 14:31:46.607 12233 12233 I BreventServer: support stopped: true
11-26 14:31:46.607 12233 12233 I BreventServer: support upgrade: checking
11-26 14:31:46.607 12233 12233 I BreventServer: support appops: true
11-26 14:31:46.607 12233 12233 I BreventServer: support disable: true
11-26 14:31:46.607 12233 12233 I BreventServer: Brevent Server 3.5.4.1 started
11-26 14:31:46.607 12233 12233 I BreventServer: sent 10 to 12229
11-26 14:31:46.613 12229 12229 I BreventLoader: received signal: 10, ppid: 12224
11-26 14:31:46.615 12224 12224 I BreventLoader: check received signal: 10, ppid: 1567
11-26 14:31:46.745 12233 12233 I BreventServer: brevent disabled packages: {}
11-26 14:31:46.761 12233 12233 I BreventServer: check and brevent
11-26 14:31:46.792 12233 12233 W BreventServer: no enqueue event, use dump to check notification
11-26 14:31:46.827 12233 12249 I BreventServer: support upgrade: true
11-26 14:31:46.918 12229 12229 E BreventLoader: worker 12233 exited on signal 9
11-26 14:31:46.918 12229 12229 I BreventLoader: signal arrived, update: 0
11-26 14:31:46.925 12224 12224 I BreventLoader: worker 12229 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by AndyWing** [comment]
com.android.server.wallpaper.WallpaperManagerService#getWallpaperInfo
签名修改后,
getWallpaperInfo(I**,I**)Landroid/app/WallpaperInfo, 第二个新增参数为displayId, 可直接使用Display.DEFULT_DISPLAY 或者 0

或者使用 android.app.WallpaperManager#getWallpaperInfo方法,无需做改动

**Comment by liudongmiao** [comment]
请帮忙看下这个测试版本，使用 dumpsys 来获取 wallpaper：

> https://jianyu.io/br/alpha/

但是，是否有获取到，就需要看日志了。日志位于 SDCARD 目录。
我仅在本地测试，以及看了下 wallpaper service 历史源码，内容基本是稳定的。

>  不使用 WallpaperManager，是因为黑阈服务所在进程没有 context。

而且，这个影响其实很小，黑阈管理界面也不许黑阈壁纸应用。

此外，如果可以找到手机厂商，可以直接请他们修复 Android 9 下前台服务可能没有通知问题。
当然，黑阈会直接强行停止没有通知的前台服务应用。

**Comment by AndyWing** [comment]
我来测试一下,需要点时间,后面再来更新反馈~

**Comment by AndyWing** [comment]
emmm..我今天用多个不同型号手机以及多个版本包括user和userdebug的rom对3.5.4.1.play & 3.5.5.play  版本进行测试, 发现这2个版本可以正常工作了?好奇怪的现象, 出问题的手机已经被我刷过一个修改api的版本了,所以不能重新测试.
上面测试的手机和版本里面就包括我跟我出问题的手机的相同型号和rom的~费解

3.5.6.alpha 也是可以正常工作了~

但是还是不知道为什么, 哈哈...尴尬

另外,关于厂商修改api导致的问题,我的反馈也有响应了

"Google is adding formal multiple display wallpaper support, so I'd assume that app will be broken in Android Q for sure if they don't update their code."  
主要是为了支持多显示器可以设置和获取不同的wallpaper才做的这个修改,后续google也会出正式版,请知悉~
多谢!
