### ISSUE TITLE
[android 9, custom rom] Can't get running app processes 

### ISSUE THREAD

**Issue by junz93** [brevent/Brevent#484]
### Device:
Galaxy S9

### OS:
Android 9 (One UI 1.0 - 3rd beta update)

### Logs:
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-Mx5dntzy_21BHvUgvjaf2Q==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '12-11 23:39:09.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-11 23:39:09.000' -d -s BreventLoader BreventServer
12-11 23:39:09.238  8569  8569 I BreventLoader: sdk: 28
12-11 23:39:09.304  8574  8574 I BreventLoader: pm path me.piebridge.brevent
12-11 23:39:09.381  8574  8574 I BreventLoader: line: package:/data/app/me.piebridge.brevent-Mx5dntzy_21BHvUgvjaf2Q==/base.apk
12-11 23:39:09.383  8574  8574 I BreventLoader: loader path: /data/app/me.piebridge.brevent-Mx5dntzy_21BHvUgvjaf2Q==/base.apk
12-11 23:39:09.385  8578  8578 I BreventLoader: start: 1544600349
12-11 23:39:09.732  8578  8578 I BreventServer: args: [10, me.piebridge.brevent, 1544600349]
12-11 23:39:09.769  8578  8578 I BreventServer: server log name: server.20181211.2339.8578.txt
12-11 23:39:09.769  8578  8578 I BreventServer: starting Brevent Server 3.5.7
12-11 23:39:09.784  8578  8578 I BreventServer: brevent version: 3.5.7
12-11 23:39:09.795  8578  8578 W BreventServer: Can't getCurrentUser
12-11 23:39:09.795  8578  8578 I BreventServer: brevent user: 0, uid: 2000
12-11 23:39:09.797  8578  8578 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
12-11 23:39:09.797  8578  8578 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.CON.do(Unknown Source:4156)
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.CON.µН(Unknown Source:4105)
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.CON.<init>(Unknown Source:395)
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.CON.do(Unknown Source:4435)
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(Unknown Source:28)
12-11 23:39:09.797  8578  8578 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
12-11 23:39:09.797  8578  8578 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(Unknown Source:64)
12-11 23:39:09.797  8578  8578 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-11 23:39:09.797  8578  8578 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
12-11 23:39:09.797  8578  8578 W BreventServer: Can't getCurrentUser
12-11 23:39:09.871  8574  8574 E BreventLoader: worker 8578 exited with status 3
12-11 23:39:09.871  8574  8574 I BreventLoader: signal arrived, update: 0
12-11 23:39:09.879  8569  8569 I BreventLoader: worker 8574 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment]
Brevent cannot get running processes. Won't support.

**Comment by liudongmiao** [comment]
support in 3.5.9
