### ISSUE TITLE
SM-G965U (S9+) Android 9.0

### ISSUE THREAD

**Issue by RamboLyk** [brevent/Brevent#488]
D:\adb>adb devices
List of devices attached
3959525741513098        device

D:\adb>adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-OUQ-tNGtdfd7G58cQ1dIbw==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '12-20 23:50:10.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '12-20 23:50:10.000' -d -s BreventLoader BreventServer
12-20 23:50:10.400 11350 11350 I BreventLoader: sdk: 28
12-20 23:50:10.433 11357 11357 I BreventLoader: pm path me.piebridge.brevent
12-20 23:50:10.517 11357 11357 I BreventLoader: line: package:/data/app/me.piebridge.brevent-OUQ-tNGtdfd7G58cQ1dIbw==/base.apk
12-20 23:50:10.521 11357 11357 I BreventLoader: loader path: /data/app/me.piebridge.brevent-OUQ-tNGtdfd7G58cQ1dIbw==/base.apk
12-20 23:50:10.525 11361 11361 I BreventLoader: start: 1545321010
12-20 23:50:11.013 11361 11361 I BreventServer: args: [10, me.piebridge.brevent, 1545321010]
12-20 23:50:11.085 11361 11361 I BreventServer: server log name: server.20181220.2350.11361.txt
12-20 23:50:11.085 11361 11361 I BreventServer: starting Brevent Server 3.5.7
12-20 23:50:11.118 11361 11361 I BreventServer: brevent version: 3.5.7
12-20 23:50:11.130 11361 11361 W BreventServer: Can't getCurrentUser
12-20 23:50:11.131 11361 11361 I BreventServer: brevent user: 0, uid: 2000
12-20 23:50:11.133 11361 11361 E BreventServer: Can't start Brevent: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
12-20 23:50:11.133 11361 11361 E BreventServer: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.CON.do(Unknown Source:4156)
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.CON.µН(Unknown Source:4105)
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.CON.<init>(Unknown Source:395)
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.CON.do(Unknown Source:4435)
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(Unknown Source:28)
12-20 23:50:11.133 11361 11361 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
12-20 23:50:11.133 11361 11361 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(Unknown Source:64)
12-20 23:50:11.133 11361 11361 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
12-20 23:50:11.133 11361 11361 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
12-20 23:50:11.133 11361 11361 W BreventServer: Can't getCurrentUser
12-20 23:50:11.167 11357 11357 E BreventLoader: worker 11361 exited with status 3
12-20 23:50:11.167 11357 11357 I BreventLoader: signal arrived, update: 0
12-20 23:50:11.175 11350 11350 I BreventLoader: worker 11357 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

D:\adb>

**Comment by vvb2060** [comment]
#484
