### ISSUE TITLE
升级至最新版v2.1.1,启动黑域失败，其中brevent步骤失败

### ISSUE THREAD

**Issue by sichaoguo21** [brevent/Brevent#6]
cmd窗口执行`adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh`后系统反馈如下：
`
--- crash start ---
```
>>> /system/bin/logcat -b crash -t '08-07 00:19:03.000' -d
E/AndroidRuntime( 8703): *** FATAL EXCEPTION IN SYSTEM PROCESS: main
E/AndroidRuntime( 8703): java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 8703):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8703):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 8703):        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2308)
E/AndroidRuntime( 8703):        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
E/AndroidRuntime( 8703):        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)
E/AndroidRuntime( 8703): Caused by: java.lang.NoSuchMethodError: No interface method setMode(IILjava/lang/String;I)V in class Lcom/android/internal/app/IAppOpsService; or its super classes (declaration of 'com.android.internal.app.IAppOpsService' appears in /system/framework/framework.jar:classes2.dex)
E/AndroidRuntime( 8703):        at me.piebridge.brevent.server.e.a(HideApi.java:754)
E/AndroidRuntime( 8703):        at me.piebridge.brevent.server.BreventServer.i(BreventServer.java:2181)
E/AndroidRuntime( 8703):        at me.piebridge.brevent.server.BreventServer.h(BreventServer.java:2135)
E/AndroidRuntime( 8703):        at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2210)
E/AndroidRuntime( 8703):        ... 5 more
E/AndroidRuntime( 8703): Error reporting crash
E/AndroidRuntime( 8703): java.lang.RuntimeException: Bad file descriptor
E/AndroidRuntime( 8703):        at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime( 8703):        at android.os.BinderProxy.transact(Binder.java:595)
E/AndroidRuntime( 8703):        at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4353)
E/AndroidRuntime( 8703):        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
E/AndroidRuntime( 8703):        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime( 8703):        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
--- crash end ---
--- brevent start ---
>>> /system/bin/logcat -b main -t '08-07 00:19:03.000' -d -s BreventLoader BreventServer
D/BreventLoader( 8685): loader path: /data/app/me.piebridge.brevent-1/base.apk
D/BreventServer( 8703): get service: package
D/BreventServer( 8703): args: [10]
I/BreventServer( 8703): signal: 10
I/BreventServer( 8703): starting Brevent Server 2.1.1
D/BreventServer( 8703): get service: package
I/BreventServer( 8703): brevent user: 0, uid: 2000
I/BreventServer( 8703): brevent data directory: /data/data/com.android.shell
I/BreventServer( 8703): loading brevent list
I/BreventServer( 8703): load /data/data/com.android.shell/me.piebridge.brevent.list, size: 67
W/BreventServer( 8703): Can't setStopped for com.appboss.LinuxShellScriptConcepts(ignore)
I/BreventServer( 8703): loading brevent conf
D/BreventServer( 8703): get service: appwidget
D/BreventServer( 8703): check and brevent
I/BreventServer( 8703): Brevent Event, now: 1502036344
D/BreventServer( 8703): get service: notification
I/BreventServer( 8703): system_server: 3039, now: 1502036344
D/BreventServer( 8703): get service: activity
D/BreventServer( 8703): get service: alarm
D/BreventServer( 8703): get service: wallpaper
I/BreventServer( 8703): won't block com.android.vending, depended by {com.google.android.gms}
D/BreventServer( 8703): Force stop com.sankuai.meituan(forceStop)
D/BreventServer( 8703): Force stop com.smartisanos.music(forceStop)
D/BreventServer( 8703): Force stop com.smartisanos.recorder(forceStop)
D/BreventServer( 8703): check again in 3600s
D/BreventServer( 8703): check and brevent, took 738ms
D/BreventServer( 8703): get service: power
I/BreventServer( 8703): charging: true
I/BreventServer( 8703): support standby: false
I/BreventServer( 8703): support stopped: false
I/BreventServer( 8703): Brevent Server 2.1.1 started
D/BreventServer( 8703): get service: appops
E/BreventLoader( 8685): worker 8703 exited on signal 9
D/BreventLoader( 8685): signal arrived, update: 0
D/BreventLoader( 8680): worker 8685 exited with status 0
```
--- brevent end ---
please report bug to https://github.com/brevent/Brevent/issues with log above`

求解！

**Comment by liudongmiao** [comment]
> E/AndroidRuntime( 8703): Caused by: java.lang.NoSuchMethodError: No interface method setMode(IILjava/lang/String;I)V in class Lcom/android/internal/app/IAppOpsService; or its super classes (declaration of 'com.android.internal.app.IAppOpsService' appears in /system/framework/framework.jar:classes2.dex)


什么魔改机器啊，没有这个 api...

**Comment by liudongmiao** [comment]
手动安装这个测试版吧：https://piebridge.me/br/next/

**Comment by viowai** [comment]
我用的锤子 T2 也是这个报错，已装 v2.1.1+1
另，
每次重启后锤子 T2 都会需要重新 adb

**Comment by liudongmiao** [comment]
@viowme 报这个错后，升级这个版本还出现么?
锤子不至于这个魔改吧？

重启肯定需要重新 adb，别想了。

**Comment by sichaoguo21** [comment]
@liudongmiao 也是锤子T2。
已装v2.1.1+1，本次开机可用，不知重启后会不会有异常；
个人感觉锤子系统搭配黑域早期版本节电效果比较明显，现在越来越不行了，后台自启照样猖獗...

**Comment by cv0cv0** [comment]
@sichaoguo21 是不是现在软件也开始针对黑域优化了？

**Comment by liudongmiao** [comment]
@sichaoguo21 什么 ROM，测试版还是稳定版？
我考虑要不要在锤子商店更新一个版本。

**Comment by liudongmiao** [comment]
@sichaoguo21 问了十八爷（锤子专版赞助人），没有什么问题，可能是非官方 rom 吧。

此问题关闭。

**Comment by sichaoguo21** [comment]
@liudongmiao 最新正式版，T2的v3.7.0.1，Android 5.1.1内核。
近来系统更新频繁，然耗电问题不减，锤友多怨言；
估计锤子小公司，精力主要放在新机型新系统（安卓7.0），但新机型如M1、坚果Pro本身配有大电池，加上新系统优化相对较好，很扛用；
真正需要关注耗电问题的反倒是T1\2等老机型，黑域有没有针对老系统的优化方案？

**Comment by sichaoguo21** [comment]
@cv0cv0 锤子低内核版本系统自己的问题，耗电太厉害，软件们都是一如既往的流氓。

**Comment by liudongmiao** [comment]
十八爷是 M1，没问题...

自己设置吧，大约如下：

1. 后台超时设小点
2. 不用的应用，直接从最近列表划掉
3. 不要轻易开激进模式，黑域系统应用、框架应用、常用应用，否则更费电

4. 少装应用，更新机器。

**Comment by sichaoguo21** [comment]
@liudongmiao 
...楼主说的这几个注意点我应该都不存在问题，
锤子现在适配新老机型的版本太多了，可能真的是系统本身的问题。

**Comment by liudongmiao** [comment]
明明你自己才是楼主...好了，别水了，篡钱买新机去吧...
