### ISSUE TITLE
黑域无法放访问本地网络

### ISSUE THREAD

**Issue by yifanli0227** [brevent/Brevent#602]
play下载的3.7.7，突然就这样了。网络设置重置过了，也开了高性能模式。黑域也没在任何黑名单里。
Note 10+ 非root。

cmd执行完了手机会提示：
黑域无法放访问本地网络，请调整网络设置，省电模式与强制低电耗（doze）等

然后cmd会有：
```
--- crash start ---
[command] logcat -b crash -t '08-26 12:31:44.000' -d
08-26 12:31:45.710  6404  6460 E AndroidRuntime: FATAL EXCEPTION: DumpPipe
08-26 12:31:45.710  6404  6460 E AndroidRuntime: PID: 6404
08-26 12:31:45.710  6404  6460 E AndroidRuntime: java.lang.StringIndexOutOfBoundsException: length=29; index=62
08-26 12:31:45.710  6404  6460 E AndroidRuntime:        at java.lang.String.substring(String.java:2032)
08-26 12:31:45.710  6404  6460 E AndroidRuntime:        at me.piebridge.brevent.server.cON.do(:7)
08-26 12:31:45.710  6404  6460 E AndroidRuntime:        at me.piebridge.brevent.server.碌渭H.run(:9)
08-26 12:31:45.710  6404  6460 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-26 12:31:44.000' -d -s BreventLoader BreventServer
08-26 12:31:44.690  6395  6395 I BreventLoader: sdk: 28
08-26 12:31:44.729  6400  6400 I BreventLoader: pm path me.piebridge.brevent
08-26 12:31:44.800  6400  6400 I BreventLoader: line: package:/data/app/me.piebridge.brevent-uxW2WKc0ro0cLvuCaQFWig==/base.apk
08-26 12:31:44.803  6400  6400 I BreventLoader: loader path: /data/app/me.piebridge.brevent-uxW2WKc0ro0cLvuCaQFWig==/base.apk
08-26 12:31:44.807  6404  6404 I BreventLoader: start: 1566837104
08-26 12:31:45.064  6404  6404 I BreventServer: args: [10, me.piebridge.brevent, 1566837104]
08-26 12:31:45.098  6404  6404 I BreventServer: server log name: server.20190826.1231.6404.txt
08-26 12:31:45.099  6404  6404 I BreventServer: starting Brevent Server 3.7.7
08-26 12:31:45.109  6404  6404 I BreventServer: brevent version: 3.7.7
08-26 12:31:45.111  6404  6404 I BreventServer: add sigcont handler
08-26 12:31:45.113  6404  6404 I BreventServer: sdk: 28, genuine: 0
08-26 12:31:45.113  6404  6404 I BreventServer: brevent user: 0, uid: 2000
08-26 12:31:45.254  6404  6404 I BreventServer: core apps: [com.sec.vsim.ericssonnsds.webapp, com.sec.location.nsflp2, com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.samsung.android.incallui, com.samsung.android.knox.containercore, com.sec.vsimservice, com.android.mms.service, com.samsung.ucs.agent.boot, com.android.defcontainer, com.sec.ims, com.sec.sve, com.samsung.android.SettingsReceiver, android, com.samsung.android.app.telephonyui, com.android.providers.settings, com.sec.imsservice, com.android.se, com.android.inputdevices, com.samsung.knox.securefolder, com.samsung.advp.imssettings, com.sec.android.inputmethod, com.android.server.telecom, com.google.android.packageinstaller, com.android.proxyhandler, com.sec.phone, com.sec.app.RilErrorNotifier, com.android.settings, com.knox.vpn.proxyhandler, com.android.phone, com.android.shell, com.android.location.fused, com.sec.epdg, com.android.systemui]
08-26 12:31:45.254  6404  6404 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.defcontainer, android, com.android.providers.settings, com.android.se, com.android.inputdevices, com.android.server.telecom, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
08-26 12:31:45.255  6404  6404 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared, com.google.android.packageinstaller}
08-26 12:31:45.256  6404  6404 I BreventServer: installer: com.google.android.packageinstaller
08-26 12:31:45.256  6404  6404 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-26 12:31:45.264  6404  6404 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.google.android.youtube, com.samsung.android.themestore, com.microsoft.appmanager, com.one97.hero, com.samsung.android.spdclient, com.scene.mobile, com.aol.mobile.engadget, com.discord, com.samsung.android.email.provider, com.sec.android.app.samsungapps, com.sec.android.app.billing, com.bmo.mobile, com.android.vending, com.microsoft.skydrive, com.tencent.mm, me.lyft.android, com.instagram.android, com.mcdonalds.superapp, com.kathleenOswald.solitaireGooglePlay, com.samsung.android.bixby.agent, com.microsoft.office.outlook, com.sec.imsservice, com.r6stats.app, com.samsung.android.kgclient, com.starbucks.mobilecard, com.ebay.kijiji.ca, digital.rbi.timhortons, com.ubercab.eats, com.samsung.android.dynamiclock, com.samsung.android.mdecservice, com.samsung.android.coldwalletservice, com.netflix.mediaclient, flipboard.boxer.app, com.sap.mdc.loblaw.nativ, com.ubercab, com.sec.android.app.sbrowser, com.fidosolutions.myaccount, com.samsung.android.oneconnect, com.samsung.android.fmm, com.sec.android.app.shealth, com.sec.penup, com.cibc.android.mobi, com.samsung.android.spay, com.netatmo.camera, com.samsung.android.mateagent, com.americanexpress.android.acctsvcs.ca, com.samsung.android.app.omcagent, com.wssyncmldm, com.google.android.apps.youtube.music, com.samsung.android.sdm.config, com.rbc.mobile.android}
08-26 12:31:45.269  6404  6404 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.amazon.mShop.android.shopping, com.google.android.youtube, com.samsung.android.themestore, com.oasisfeng.greenify, com.microsoft.appmanager, com.google.android.googlequicksearchbox, com.one97.hero, com.samsung.android.spdclient, com.scene.mobile, com.samsung.android.service.tagservice, com.wdc.mycloud, com.aol.mobile.engadget, com.discord, com.samsung.android.email.provider, com.sec.android.app.samsungapps, org.joa.zipperplus7, com.sec.android.app.billing, com.bmo.mobile, com.samsung.android.game.gamehome, com.google.ar.core, com.android.vending, com.microsoft.skydrive, com.tencent.mm, android, me.piebridge.brevent, me.lyft.android, com.instagram.android, com.mcdonalds.superapp, com.fivemobile.cineplex, com.kathleenOswald.solitaireGooglePlay, com.samsung.android.bixby.agent, com.microsoft.office.outlook, com.sec.imsservice, com.google.android.music, com.samsung.android.mobileservice, com.sec.android.app.music, com.r6stats.app, com.samsung.android.kgclient, com.starbucks.mobilecard, com.ebay.kijiji.ca, digital.rbi.timhortons, com.dmm.app.rplayer, com.google.android.apps.docs, com.google.android.apps.maps, com.ubercab.eats, com.samsung.android.dynamiclock, com.samsung.android.mdecservice, com.synology.DSfile, com.android.chrome, com.google.android.gms, com.google.android.gsf, com.samsung.android.coldwalletservice, com.google.android.apps.walletnfcrel, com.google.android.videos, com.netflix.mediaclient, flipboard.boxer.app, com.google.android.apps.photos, com.sap.mdc.loblaw.nativ, com.samsung.android.authfw, com.ubercab, com.sec.android.app.sbrowser, com.amazon.avod.thirdpartyclient, com.fidosolutions.myaccount, com.samsung.android.oneconnect, com.samsung.android.fmm, com.sec.android.app.shealth, com.sec.penup, com.samsung.android.app.soundpicker, com.cibc.android.mobi, com.samsung.android.spay, com.netatmo.camera, com.google.android.apps.turbo, com.samsung.android.mateagent, com.americanexpress.android.acctsvcs.ca, com.samsung.android.app.omcagent, com.wssyncmldm, com.google.android.apps.youtube.music, com.google.android.play.games, com.samsung.android.sdm.config, com.rbc.mobile.android, com.youdao.translator, com.cnbeta.client, com.google.android.apps.restore}
08-26 12:31:45.269  6404  6404 I BreventServer: fcm: {com.google.android.youtube, com.samsung.android.themestore, com.microsoft.appmanager, com.one97.hero, com.samsung.android.spdclient, com.scene.mobile, com.aol.mobile.engadget, com.discord, com.samsung.android.email.provider, com.sec.android.app.samsungapps, com.sec.android.app.billing, com.bmo.mobile, com.android.vending, com.microsoft.skydrive, com.tencent.mm, me.lyft.android, com.instagram.android, com.mcdonalds.superapp, com.kathleenOswald.solitaireGooglePlay, com.samsung.android.bixby.agent, com.microsoft.office.outlook, com.sec.imsservice, com.r6stats.app, com.samsung.android.kgclient, com.starbucks.mobilecard, com.ebay.kijiji.ca, digital.rbi.timhortons, com.ubercab.eats, com.samsung.android.dynamiclock, com.samsung.android.mdecservice, com.samsung.android.coldwalletservice, com.netflix.mediaclient, flipboard.boxer.app, com.sap.mdc.loblaw.nativ, com.ubercab, com.sec.android.app.sbrowser, com.fidosolutions.myaccount, com.samsung.android.oneconnect, com.samsung.android.fmm, com.sec.android.app.shealth, com.sec.penup, com.cibc.android.mobi, com.samsung.android.spay, com.netatmo.camera, com.samsung.android.mateagent, com.americanexpress.android.acctsvcs.ca, com.samsung.android.app.omcagent, com.wssyncmldm, com.google.android.apps.youtube.music, com.samsung.android.sdm.config, com.rbc.mobile.android}
08-26 12:31:45.271  6404  6404 W BreventServer: Can't getState
08-26 12:31:45.271  6404  6404 W BreventServer: java.lang.IllegalArgumentException: Unknown package: com.hp.android.printservice
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.os.Parcel.createException(Parcel.java:1970)
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.os.Parcel.readException(Parcel.java:1934)
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.os.Parcel.readException(Parcel.java:1884)
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.content.pm.IPackageManager$Stub$Proxy.getApplicationEnabledSetting(IPackageManager.java:5929)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.碌渭巍.碌袧(:1)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.CON.螚P(:1)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.CON.碌螚(:24)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.CON.<init>(:62)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.CON.do(:650)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.碌螚H.do(:5)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.BreventServer.main(:1)
08-26 12:31:45.271  6404  6404 W BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.碌螚H.do(:21)
08-26 12:31:45.271  6404  6404 W BreventServer:         at me.piebridge.brevent.server.BreventServer.main(:2)
08-26 12:31:45.271  6404  6404 W BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-26 12:31:45.271  6404  6404 W BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:341)
08-26 12:31:45.271  6404  6404 W BreventServer: Caused by: android.os.RemoteException: Remote stack trace:
08-26 12:31:45.271  6404  6404 W BreventServer:         at com.android.server.pm.Settings.getApplicationEnabledSettingLPr(Settings.java:4704)
08-26 12:31:45.271  6404  6404 W BreventServer:         at com.android.server.pm.PackageManagerService.getApplicationEnabledSetting(PackageManagerService.java:25697)
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1871)
08-26 12:31:45.271  6404  6404 W BreventServer:         at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4846)
08-26 12:31:45.271  6404  6404 W BreventServer:         at android.os.Binder.execTransact(Binder.java:739)
08-26 12:31:45.271  6404  6404 W BreventServer:
08-26 12:31:45.271  6404  6404 W BreventServer: ignore invalid brevented app: com.hp.android.printservice
08-26 12:31:45.272  6404  6404 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 22
08-26 12:31:45.275  6404  6404 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
08-26 12:31:45.275  6404  6404 I BreventServer: disabling: {}
08-26 12:31:45.275  6404  6404 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 19
08-26 12:31:45.275  6404  6404 I BreventServer: ppid: 6400
08-26 12:31:45.276  6404  6404 I BreventServer: checking standby, sdk: 28
08-26 12:31:45.286  6404  6404 I BreventServer: init widgets
08-26 12:31:45.293  6404  6404 I BreventServer: init notifications
08-26 12:31:45.310  6404  6404 I BreventServer: recents package name: com.sec.android.app.launcher
08-26 12:31:45.320  6404  6404 I BreventServer: use com.sec.vsim.ericssonnsds.webapp to check upgrade and disable
08-26 12:31:45.320  6404  6404 I BreventServer: update com.sec.vsim.ericssonnsds.webapp to disabled-user, new state: disabled-user
08-26 12:31:45.322  6404  6404 I BreventServer: update com.sec.vsim.ericssonnsds.webapp to enabled, new state: enabled
08-26 12:31:45.337  6404  6423 I BreventServer: system_server: 1343
08-26 12:31:45.337  6404  6423 I BreventServer: android_log_clockid: 0x7931995224
08-26 12:31:45.337  6404  6423 I BreventServer: clockid: 0, realtime: 0
08-26 12:31:45.337  6404  6423 I BreventServer: system_server: 1343, now: 1566837105
08-26 12:31:45.365  6404  6404 I BreventServer: support standby: true
08-26 12:31:45.365  6404  6404 I BreventServer: support stopped: true
08-26 12:31:45.365  6404  6404 I BreventServer: support upgrade: checking
08-26 12:31:45.365  6404  6404 I BreventServer: support appops: true
08-26 12:31:45.365  6404  6404 I BreventServer: support disable: true
08-26 12:31:45.370  6404  6404 I BreventServer: Brevent Server 3.7.7 started
08-26 12:31:45.370  6404  6404 I BreventServer: sent 10 to 6400
08-26 12:31:45.371  6400  6400 I BreventLoader: received signal: 10, ppid: 6395
08-26 12:31:45.371  6395  6395 I BreventLoader: check received signal: 10, ppid: 2344
08-26 12:31:45.633  6404  6423 I BreventServer: support upgrade: true
08-26 12:31:45.663  6404  6404 I BreventServer: brevent disabled packages: {}
08-26 12:31:45.664  6404  6429 W BreventServer: no enqueue event, use dump to check notification
08-26 12:31:45.668  6404  6404 I BreventServer: received first event
08-26 12:31:45.691  6404  6460 W BreventServer: Can't get uid for /proc/14853
08-26 12:31:45.691  6404  6460 W BreventServer: android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
08-26 12:31:45.691  6404  6460 W BreventServer:         at libcore.io.Linux.stat(Native Method)
08-26 12:31:45.691  6404  6460 W BreventServer:         at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
08-26 12:31:45.691  6404  6460 W BreventServer:         at android.system.Os.stat(Os.java:565)
08-26 12:31:45.691  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭巍.碌袧(:10)
08-26 12:31:45.691  6404  6460 W BreventServer:         at me.piebridge.brevent.server.cON.do(:11)
08-26 12:31:45.691  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭H.run(:9)
08-26 12:31:45.691  6404  6460 W BreventServer:         at java.lang.Thread.run(Thread.java:764)
08-26 12:31:45.695  6404  6460 W BreventServer: Can't get uid for /proc/14853
08-26 12:31:45.695  6404  6460 W BreventServer: android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
08-26 12:31:45.695  6404  6460 W BreventServer:         at libcore.io.Linux.stat(Native Method)
08-26 12:31:45.695  6404  6460 W BreventServer:         at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
08-26 12:31:45.695  6404  6460 W BreventServer:         at android.system.Os.stat(Os.java:565)
08-26 12:31:45.695  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭巍.碌袧(:10)
08-26 12:31:45.695  6404  6460 W BreventServer:         at me.piebridge.brevent.server.cON.do(:11)
08-26 12:31:45.695  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭H.run(:9)
08-26 12:31:45.695  6404  6460 W BreventServer:         at java.lang.Thread.run(Thread.java:764)
08-26 12:31:45.707  6404  6460 W BreventServer: Can't get uid for /proc/14853
08-26 12:31:45.707  6404  6460 W BreventServer: android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
08-26 12:31:45.707  6404  6460 W BreventServer:         at libcore.io.Linux.stat(Native Method)
08-26 12:31:45.707  6404  6460 W BreventServer:         at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
08-26 12:31:45.707  6404  6460 W BreventServer:         at android.system.Os.stat(Os.java:565)
08-26 12:31:45.707  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭巍.碌袧(:10)
08-26 12:31:45.707  6404  6460 W BreventServer:         at me.piebridge.brevent.server.cON.do(:11)
08-26 12:31:45.707  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭H.run(:9)
08-26 12:31:45.707  6404  6460 W BreventServer:         at java.lang.Thread.run(Thread.java:764)
08-26 12:31:45.709  6404  6460 W BreventServer: Can't get uid for /proc/14853
08-26 12:31:45.709  6404  6460 W BreventServer: android.system.ErrnoException: stat failed: ENOENT (No such file or directory)
08-26 12:31:45.709  6404  6460 W BreventServer:         at libcore.io.Linux.stat(Native Method)
08-26 12:31:45.709  6404  6460 W BreventServer:         at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
08-26 12:31:45.709  6404  6460 W BreventServer:         at android.system.Os.stat(Os.java:565)
08-26 12:31:45.709  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭巍.碌袧(:10)
08-26 12:31:45.709  6404  6460 W BreventServer:         at me.piebridge.brevent.server.cON.do(:11)
08-26 12:31:45.709  6404  6460 W BreventServer:         at me.piebridge.brevent.server.碌渭H.run(:9)
08-26 12:31:45.709  6404  6460 W BreventServer:         at java.lang.Thread.run(Thread.java:764)
08-26 12:31:45.743  6400  6400 E BreventLoader: worker 6404 exited on signal 9
08-26 12:31:45.743  6400  6400 I BreventLoader: signal arrived, update: 0
08-26 12:31:45.746  6395  6395 I BreventLoader: worker 6400 exited with status 0
--- brevent end ---
```

**Comment by liudongmiao** [comment]
这个错误与 音乐播放检查 相关。

你可以清空黑阈数据，不要开启 优化音乐功能。

或者 升级 最新 alpha 版：https://jianyu.io/br/alpha/

最近小米魔改越来越厉害了啊...

**Comment by liudongmiao** [comment]
请邮件至 brevent@jianyu.io，表明身份，获取特别贡献兑换码。
