### ISSUE TITLE
黑域端口被占用无法激活

### ISSUE THREAD

**Issue by p781110583** [brevent/Brevent#606]
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-fA4sRZPzbSENIZd6m4AW4g==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '09-13 10:33:02.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-13 10:33:02.000' -d -s BreventLoader BreventServer
09-13 10:33:02.926 24992 24992 I BreventLoader: sdk: 28
09-13 10:33:02.962 25010 25010 I BreventLoader: pm path me.piebridge.brevent
09-13 10:33:02.989 25010 25010 I BreventLoader: line: package:/data/app/me.piebridge.brevent-fA4sRZPzbSENIZd6m4AW4g==/base.apk
09-13 10:33:02.992 25010 25010 I BreventLoader: loader path: /data/app/me.piebridge.brevent-fA4sRZPzbSENIZd6m4AW4g==/base.apk
09-13 10:33:02.993 25018 25018 I BreventLoader: start: 1568341982
09-13 10:33:03.411 25018 25018 I BreventServer: args: [10, me.piebridge.brevent, 1568341982]
09-13 10:33:03.504 25018 25018 I BreventServer: server log name: server.20190913.1033.25018.txt
09-13 10:33:03.505 25018 25018 I BreventServer: starting Brevent Server 3.5.7
09-13 10:33:03.545 25018 25018 I BreventServer: brevent version: 3.5.7
09-13 10:33:03.559 25018 25018 I BreventServer: brevent user: 0, uid: 2000
09-13 10:33:03.564 25018 25018 E BreventServer: Can't get running app processes
09-13 10:33:03.564 25018 25018 E BreventServer: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo com.android.server.am.ProcessRecord.info' on a null object reference
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.os.Parcel.createException(Parcel.java:1956)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:1918)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:1868)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.app.IActivityManager$Stub$Proxy.getRunningAppProcesses(IActivityManager.java:5309)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.碌渭巍.if(Unknown Source:123)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.CON.do(Unknown Source:4156)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.CON.碌袧(Unknown Source:4105)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.CON.<init>(Unknown Source:395)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.CON.do(Unknown Source:4435)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:28)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(Unknown Source:64)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:384)
09-13 10:33:03.564 25018 25018 E BreventServer: Caused by: android.os.RemoteException: Remote stack trace:
09-13 10:33:03.564 25018 25018 E BreventServer: 	at com.android.server.am.ActivityManagerService.getRunningAppProcesses(ActivityManagerService.java:17920)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:1011)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3826)
09-13 10:33:03.564 25018 25018 E BreventServer: 	at android.os.Binder.execTransact(Binder.java:752)
09-13 10:33:03.564 25018 25018 E BreventServer: 
09-13 10:33:03.586 25010 25010 E BreventLoader: worker 25018 exited with status 3
09-13 10:33:03.586 25010 25010 I BreventLoader: signal arrived, update: 0
09-13 10:33:03.587 24992 24992 I BreventLoader: worker 25010 exited with status 0
--- brevent end ---
```
</details><br/>

**Comment by vvb2060** [comment]
不对旧版本提供支持，请升级。

**Comment by liudongmiao** [comment]
版本太老。

请至 https://brevent.jianyu.io 下载最新版本。

也和端口占用无关。
