### ISSUE TITLE
Android11(MIUI12 20.8.13)开启失败

### ISSUE THREAD

**Issue by tsfksj** [brevent/Brevent#665]
<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '08-14 14:53:03.000' -d
--------- beginning of crash
08-14 14:53:04.105 30959 30959 E AndroidRuntime: FATAL EXCEPTION: main
08-14 14:53:04.105 30959 30959 E AndroidRuntime: PID: 30959
08-14 14:53:04.105 30959 30959 E AndroidRuntime: java.lang.reflect.InvocationTargetException
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HНP.new(:25)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(:2)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
08-14 14:53:04.105 30959 30959 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method isAppInactive(Ljava/lang/String;I)Z in class Landroid/app/usage/IUsageStatsManager; or its super classes (declaration of 'android.app.usage.IUsageStatsManager' appears in /system/framework/framework.jar)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HΗP.НH(:1)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HPµ.ΗHΡ(:5)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HPµ.НHµ(:1)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HPµ.Hμ(:7)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HPµ.HН(:4)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HPµ.ΡΗµ(:97)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.HНP.for(:5)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(:1)
08-14 14:53:04.105 30959 30959 E AndroidRuntime:        ... 5 more
08-14 14:53:04.106 30959 30959 E AndroidRuntime: Error reporting crash
08-14 14:53:04.106 30959 30959 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:540)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5306)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:222)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
08-14 14:53:04.106 30959 30959 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-14 14:53:03.000' -d -s BreventLoader BreventServer
--------- beginning of main
08-14 14:53:03.124 30949 30949 I BreventLoader: sdk: 30
08-14 14:53:03.163 30954 30954 I BreventLoader: pm path me.piebridge.brevent
08-14 14:53:03.217 30954 30954 I BreventLoader: line: package:/data/app/~~lT4Qk4QPcwiaaeQbGOdrBQ==/me.piebridge.brevent-uGvXhz_kbTOGp--2izuDbw==/base.apk
08-14 14:53:03.218 30954 30954 I BreventLoader: loader path: /data/app/~~lT4Qk4QPcwiaaeQbGOdrBQ==/me.piebridge.brevent-uGvXhz_kbTOGp--2izuDbw==/base.apk
08-14 14:53:03.220 30959 30959 I BreventLoader: start: 1597387983
08-14 14:53:03.483 30959 30959 I BreventServer: args: [10, me.piebridge.brevent, 1597387983, true]
08-14 14:53:03.535 30959 30959 I BreventServer: server log name: server.20200814.1453.30959.txt
08-14 14:53:03.535 30959 30959 I BreventServer: starting Brevent Server 4.1.9
08-14 14:53:03.569 30959 30959 I BreventServer: app_suspended_default_message, orig: %1$s目前无法使用。该应用是由%2$s所管理。, now: %1$s目前无法使用。该应用是由黑阈所管理。
08-14 14:53:03.570 30959 30959 I BreventServer: brevent version: 4.1.9
08-14 14:53:03.572 30959 30959 I BreventServer: add sigcont handler
08-14 14:53:03.577 30959 30959 I BreventServer: sdk: 30, genuine: 0
08-14 14:53:03.578 30959 30959 I BreventServer: brevent user: 0, uid: 2000
08-14 14:53:03.724 30959 30959 I BreventServer: core apps: {com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.miui.packageinstaller, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, com.miui.systemAdSolution, android.qvaoverlay.common, com.android.settings.overlay.miui, android.overlay.common, com.wapi.wapicertmanage, android, android.miui.overlay, com.android.ons, org.codeaurora.ims, com.qualcomm.qti.dynamicddsservice, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.miui.face.overlay.miui, com.android.server.telecom, com.android.server.telecom.overlay.miui, com.android.wifi.resources, com.android.phone.overlay.common, com.qualcomm.qti.qtisystemservice, android.aosp.overlay, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.proxyhandler, com.xiaomi.misettings, com.google.android.documentsui, com.miui.securityinputmethod, com.android.settings, com.qualcomm.qti.cne, com.modemdebug, com.android.phone, com.android.shell, com.qualcomm.qti.seccamservice, com.android.location.fused, com.android.systemui, com.qualcomm.qti.poweroffalarm, com.android.permissioncontroller}
08-14 14:53:03.724 30959 30959 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.settings.overlay.miui, android, com.android.ons, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.android.server.telecom, com.android.server.telecom.overlay.miui, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.android.permissioncontroller}
08-14 14:53:03.725 30959 30959 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared}
08-14 14:53:03.729 30959 30959 I BreventServer: installer: com.miui.packageinstaller
08-14 14:53:03.741 30959 30959 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
08-14 14:53:03.771 30959 30959 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.microblink.photomath, com.android.vending, com.tencent.mm, com.google.android.gm, org.mozilla.firefox_beta}
08-14 14:53:03.774 30959 30959 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {org.getlantern.lantern, com.microblink.photomath, org.zwanoo.android.speedtest, com.android.vending, com.tencent.mm, android, me.piebridge.brevent, com.google.android.gm, com.apkcombo.app, com.google.android.gms, com.google.android.gsf, org.mozilla.firefox_beta, com.google.android.inputmethod.latin}
08-14 14:53:03.775 30959 30959 I BreventServer: fcm: {com.microblink.photomath, com.android.vending, com.tencent.mm, com.google.android.gm, org.mozilla.firefox_beta}
08-14 14:53:03.783 30959 30959 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 31
08-14 14:53:03.789 30959 30959 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
08-14 14:53:03.789 30959 30959 I BreventServer: disabling: {}
08-14 14:53:03.791 30959 30959 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 14
08-14 14:53:03.791 30959 30959 I BreventServer: ppid: 30954
08-14 14:53:03.791 30959 30959 I BreventServer: checking standby, sdk: 30
08-14 14:53:03.794 30959 30959 I BreventServer: init widgets
08-14 14:53:03.799 30959 30959 W BreventServer: no widgets
08-14 14:53:03.799 30959 30959 I BreventServer: init notifications
08-14 14:53:03.815 30959 30959 I BreventServer: recents package name: com.miui.home
08-14 14:53:03.839 30959 30959 I BreventServer: use com.android.cts.priv.ctsshim to check upgrade and disable
08-14 14:53:03.840 30959 30959 I BreventServer: update com.android.cts.priv.ctsshim to disabled-user, new state: disabled-user
08-14 14:53:03.840 30959 30959 I BreventServer: update com.android.cts.priv.ctsshim to enabled, new state: enabled
08-14 14:53:03.855 30959 30980 I BreventServer: system_server: 1775
08-14 14:53:03.855 30959 30980 I BreventServer: system_server: 1775, now: 1597387983
08-14 14:53:03.869 30959 30959 I BreventServer: use com.android.browser to check suspend
08-14 14:53:03.877 30959 30959 I BreventServer: package com.android.browser suspended state: true
08-14 14:53:03.878 30959 30959 I BreventServer: package com.android.browser suspended state: false
08-14 14:53:03.886 30959 30959 I BreventServer: granted permission
08-14 14:53:03.940 30959 30959 I BreventServer: uid: 10299
08-14 14:53:03.959 30959 30959 I BreventServer: registerProcessObserver
08-14 14:53:03.961 30959 30959 I BreventServer: registerUidObserver
08-14 14:53:03.961 30959 30959 I BreventServer: support standby: true
08-14 14:53:03.962 30959 30959 I BreventServer: support stopped: true
08-14 14:53:03.962 30959 30959 I BreventServer: support upgrade: checking
08-14 14:53:03.962 30959 30959 I BreventServer: support appops: true
08-14 14:53:03.962 30959 30959 I BreventServer: support disable: true
08-14 14:53:03.962 30959 30959 I BreventServer: support suspend: true
08-14 14:53:03.962 30959 30959 I BreventServer: Brevent Server 4.1.9 started
08-14 14:53:03.962 30954 30954 I BreventLoader: received signal: 10, ppid: 30949
08-14 14:53:03.962 30959 30959 I BreventServer: sent 10 to 30954
08-14 14:53:03.962 30949 30949 I BreventLoader: check received signal: 10, ppid: 2444
08-14 14:53:04.048 30959 30980 I BreventServer: support upgrade: true
08-14 14:53:04.078 30959 30972 W BreventServer: no enqueue event, use dump to check notification
08-14 14:53:04.100 30959 30959 I BreventServer: brevent disabled packages: {}
08-14 14:53:04.118 30954 30954 I BreventLoader: worker 30959 was ok, exited on signal 9, will try again
08-14 14:53:04.118 30954 30954 I BreventLoader: signal arrived, update: 1
08-14 14:53:04.118 30954 30954 I BreventLoader: will start worker in 8 seconds
--- brevent end ---
```
</details><br/>

**Comment by vvb2060** [comment]
升级到最新版本，目前是4.1.12。
