### ISSUE TITLE
红米K20 Pro更新MIUI12.5.4（android 11）后无法激活黑阈3.7.2

### ISSUE THREAD

**Issue by liu870825yi** [brevent/Brevent#717]
<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '06-14 17:59:46.000' -d
--------- beginning of crash
06-14 17:59:47.437 14590 14590 E AndroidRuntime: FATAL EXCEPTION: main
06-14 17:59:47.437 14590 14590 E AndroidRuntime: PID: 14590
06-14 17:59:47.437 14590 14590 E AndroidRuntime: java.lang.reflect.InvocationTargetException
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.碌螚巍.do(:21)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:463)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No interface method isAppInactive(Ljava/lang/String;I)Z in class Landroid/app/usage/IUsageStatsManager; or its super classes (declaration of 'android.app.usage.IUsageStatsManager' appears in /system/framework/framework.jar)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.碌螚渭.do(:20)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.do(:123)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.do(:118)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.do(:172)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.碌渭(:111)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.do(:672)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.碌螚巍.do(:5)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:1)
06-14 17:59:47.437 14590 14590 E AndroidRuntime: 	... 5 more
06-14 17:59:47.440 14590 14590 E AndroidRuntime: Error reporting crash
06-14 17:59:47.440 14590 14590 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:593)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5413)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:222)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-14 17:59:47.440 14590 14590 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-14 17:59:46.000' -d -s BreventLoader BreventServer
--------- beginning of main
06-14 17:59:46.590 14580 14580 I BreventLoader: sdk: 30
06-14 17:59:46.606 14585 14585 I BreventLoader: pm path me.piebridge.brevent
06-14 17:59:46.621 14585 14585 I BreventLoader: line: package:/data/app/me.piebridge.brevent-_FbosDILt67x-soJeufMkw==/base.apk
06-14 17:59:46.622 14585 14585 I BreventLoader: loader path: /data/app/me.piebridge.brevent-_FbosDILt67x-soJeufMkw==/base.apk
06-14 17:59:46.623 14590 14590 I BreventLoader: start: 1623664786
06-14 17:59:46.806 14590 14590 I BreventServer: args: [10, me.piebridge.brevent, 1623664786]
06-14 17:59:46.858 14590 14590 I BreventServer: server log name: server.20210614.1759.14590.txt
06-14 17:59:46.860 14590 14590 I BreventServer: starting Brevent Server 3.7.2
06-14 17:59:46.883 14590 14590 I BreventServer: brevent version: 3.7.2
06-14 17:59:46.889 14590 14590 I BreventServer: add sigcont handler
06-14 17:59:46.893 14590 14590 I BreventServer: sdk: 30, genuine: 0
06-14 17:59:46.894 14590 14590 I BreventServer: brevent user: 0, uid: 2000
06-14 17:59:47.043 14590 14590 I BreventServer: core apps: [com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.miui.packageinstaller, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, com.miui.systemAdSolution, android.qvaoverlay.common, com.android.settings.overlay.miui, android.overlay.common, com.wapi.wapicertmanage, android, android.miui.overlay, com.android.ons, org.codeaurora.ims, com.qualcomm.qti.dynamicddsservice, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.miui.face.overlay.miui, com.android.server.telecom, com.android.server.telecom.overlay.miui, com.android.wifi.resources, com.android.phone.overlay.common, com.qualcomm.qti.qtisystemservice, android.aosp.overlay, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.qualcomm.qti.devicestatisticsservice, com.android.proxyhandler, com.xiaomi.misettings, com.google.android.documentsui, com.miui.securityinputmethod, com.android.settings, com.qualcomm.qti.cne, com.android.phone, com.android.shell, com.qualcomm.qti.seccamservice, com.android.location.fused, com.android.systemui, com.qualcomm.qti.poweroffalarm, com.android.permissioncontroller]
06-14 17:59:47.043 14590 14590 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, com.android.settings.overlay.miui, android, com.android.ons, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.systemui.overlay.miui, com.android.server.telecom, com.android.server.telecom.overlay.miui, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.android.permissioncontroller}
06-14 17:59:47.044 14590 14590 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared}
06-14 17:59:47.045 14590 14590 I BreventServer: installer: com.miui.packageinstaller
06-14 17:59:47.045 14590 14590 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
06-14 17:59:47.088 14590 14590 I BreventServer: com.google.firebase.MESSAGING_EVENT: {org.potato.messenger, com.android.vending, com.tencent.mm, com.duokan.phone.remotecontroller, org.mozilla.firefox, com.taptap, com.xiaomi.smarthome}
06-14 17:59:47.090 14590 14590 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {org.potato.messenger, com.android.vending, com.tencent.mm, android, me.piebridge.brevent, com.duokan.phone.remotecontroller, com.google.android.gms, com.google.android.gsf, com.getsurfboard, org.mozilla.firefox, com.google.android.inputmethod.pinyin, com.taptap, com.google.android.inputmethod.japanese, com.xiaomi.smarthome}

06-14 17:59:47.090 14590 14590 I BreventServer: fcm: {org.potato.messenger, com.android.vending, com.tencent.mm, com.duokan.phone.remotecontroller, org.mozilla.firefox, com.taptap, com.xiaomi.smarthome}
06-14 17:59:47.096 14590 14590 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 30
06-14 17:59:47.102 14590 14590 I BreventServer: android.net.wifi.RSSI_CHANGED: {}
06-14 17:59:47.107 14590 14590 I BreventServer: android.net.conn.CONNECTIVITY_CHANGE: {com.miui.powerkeeper, com.xiaomi.vipaccount, com.qiyi.video, com.xiaomi.account, com.migu.music.mini, com.xiaomi.gamecenter.sdk.service, com.miui.gallery, com.android.quicksearchbox, com.android.providers.downloads, com.xiaomi.payment, com.miui.systemAdSolution, com.miui.tsmclient, com.miui.userguide, com.tencent.mm, com.xiaomi.jr, com.miui.hybrid, com.lionmobi.powerclean, com.android.mms, com.mfashiongallery.emag, com.miui.miservice, com.xiaomi.mifisecurity, com.android.calendar, com.miui.virtualsim, com.miui.personalassistant, com.tencent.qqlive, com.miui.bugreport, com.tencent.tim, com.mipay.wallet, com.xiaomi.pass, com.xiaomi.shop, com.google.android.gms, com.xiaomi.finddevice, com.miui.newhome, com.miui.nextpay, com.miui.video, com.xiaomi.market, com.miui.hybrid.accessory, com.coolapk.market, com.xiaomi.youpin, com.xiaomi.gamecenter, com.umiao.app, com.miui.analytics, com.android.settings, com.miui.weather2, com.taptap, com.autonavi.minimap, com.duokan.reader, com.moji.mjweather, com.android.email, com.sina.weibo, com.miui.smarttravel, com.android.deskclock, com.android.thememanager, com.taobao.taobao, com.xiaomi.smarthome, com.netease.cloudmusic, com.eg.android.AlipayGphone, cn.wps.moffice_eng}
06-14 17:59:47.107 14590 14590 I BreventServer: bad receivers: {com.autonavi.minimap, com.eg.android.AlipayGphone}
06-14 17:59:47.108 14590 14590 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
06-14 17:59:47.108 14590 14590 I BreventServer: disabling: {}
06-14 17:59:47.108 14590 14590 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 12
06-14 17:59:47.108 14590 14590 I BreventServer: ppid: 14585
06-14 17:59:47.109 14590 14590 I BreventServer: checking standby, sdk: 30
06-14 17:59:47.117 14590 14590 I BreventServer: init widgets
06-14 17:59:47.121 14590 14590 W BreventServer: no widgets
06-14 17:59:47.122 14590 14590 I BreventServer: init notifications
06-14 17:59:47.129 14590 14590 I BreventServer: recents package name: com.miui.home
06-14 17:59:47.138 14590 14590 W BreventServer: EventTag wanted 15, found 11
06-14 17:59:47.144 14590 14590 I BreventServer: use android.qvaoverlay.common to check upgrade and disable
06-14 17:59:47.144 14590 14590 I BreventServer: update android.qvaoverlay.common to disabled-user, new state: disabled-user
06-14 17:59:47.145 14590 14590 I BreventServer: update android.qvaoverlay.common to enabled, new state: enabled
06-14 17:59:47.158 14590 14612 I BreventServer: system_server: 1788
06-14 17:59:47.159 14590 14612 I BreventServer: android_log_clockid: 0x0
06-14 17:59:47.159 14590 14612 I BreventServer: clockid: 0, realtime: 0
06-14 17:59:47.159 14590 14612 I BreventServer: system_server: 1788, now: 1623664787
06-14 17:59:47.223 14590 14590 I BreventServer: support standby: true
06-14 17:59:47.223 14590 14590 I BreventServer: support stopped: true
06-14 17:59:47.223 14590 14590 I BreventServer: support upgrade: checking
06-14 17:59:47.223 14590 14590 I BreventServer: support appops: true
06-14 17:59:47.224 14590 14590 I BreventServer: support disable: true
06-14 17:59:47.224 14590 14590 I BreventServer: Brevent Server 3.7.2 started
06-14 17:59:47.224 14590 14590 I BreventServer: sent 10 to 14585
06-14 17:59:47.224 14585 14585 I BreventLoader: received signal: 10, ppid: 14580
06-14 17:59:47.224 14580 14580 I BreventLoader: check received signal: 10, ppid: 2456
06-14 17:59:47.375 14590 14615 E BreventServer: cannot parse activities
06-14 17:59:47.375 14590 14615 E BreventServer: Can't check running activities
06-14 17:59:47.376 14590 14615 E BreventServer: Can't check running activities, check again in 30s
06-14 17:59:47.432 14590 14590 I BreventServer: brevent disabled packages: {}
06-14 17:59:47.438 14590 14615 E BreventServer: Can't check running activities
06-14 17:59:47.440 14590 14615 W BreventServer: no enqueue event, use dump to check notification
06-14 17:59:47.481 14585 14585 E BreventLoader: worker 14590 exited on signal 9
06-14 17:59:47.481 14585 14585 I BreventLoader: signal arrived, update: 0
06-14 17:59:47.483 14580 14580 I BreventLoader: worker 14585 exited with status 0
--- brevent end ---
```
</details><br/>

以上是日志，之前可以usb激活的，今天更新了系统不能激活了

**Comment by vvb2060** [comment]
更新黑阈
