### ISSUE TITLE
app keep crashing in android 12 (SPB2.210513.011)

### ISSUE THREAD

**Issue by RussllGo87** [brevent/Brevent#723]
app keep crashing on my Pixel 4a 
android 12 beta 2 (SPB2.210513.011)
<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '06-25 09:04:15.000' -d
--------- beginning of crash
06-25 09:04:17.387   933   948 E AndroidRuntime: FATAL EXCEPTION: Binder:933_2
06-25 09:04:17.387   933   948 E AndroidRuntime: PID: 933
06-25 09:04:17.387   933   948 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method queryUsageStats(IJJLjava/lang/String;)Landroid/content/pm/ParceledListSlice; in class Landroid/app/usage/IUsageStatsManager; or its super classes (declaration of 'android.app.usage.IUsageStatsManager' appears in /system/framework/framework.jar)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.µΡΗ(:8)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.µμH(:28)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.µΡH(:20)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.HμP(:12)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.HНP(:4)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.HPΗ.HΡP(:2)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.do(:11)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.HPμ.CoN.HΗμ$coN.onTransact(:5)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at me.piebridge.brevent.server.AUX.onTransact(:1)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1184)
06-25 09:04:17.387   933   948 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1143)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-25 09:04:15.000' -d -s BreventLoader BreventServer
--------- beginning of main
06-25 09:04:15.579   867   867 I BreventLoader: sdk: 30
06-25 09:04:15.647   872   872 I BreventLoader: pm path me.piebridge.brevent
06-25 09:04:15.682   872   872 I BreventLoader: line: package:/data/app/~~VrTlZQCunFbRsnhng55ydg==/me.piebridge.brevent-BYIA_gSWU2EsXafz0h_v_w==/base.apk
06-25 09:04:15.687   872   872 I BreventLoader: loader path: /data/app/~~VrTlZQCunFbRsnhng55ydg==/me.piebridge.brevent-BYIA_gSWU2EsXafz0h_v_w==/base.apk
06-25 09:04:15.688   933   933 I BreventLoader: start: 1624626255
06-25 09:04:15.884   933   933 I BreventServer: args: [10, me.piebridge.brevent, 1624626255, true]
06-25 09:04:15.958   933   933 I BreventServer: server log name: server.20210625.0904.933.txt
06-25 09:04:15.959   933   933 I BreventServer: starting Brevent Server 4.2.6
06-25 09:04:16.123   933   933 I BreventServer: app_suspended_default_message, orig: %1$s isn’t available right now. This is managed by %2$s., now: %1$s isn’t available right now. This is managed by Brevent.
06-25 09:04:16.125   933   933 I BreventServer: brevent version: 4.2.6
06-25 09:04:16.133   933   933 I BreventServer: add sigcont handler
06-25 09:04:16.136   933   933 I BreventServer: sdk: 30, genuine: 0
06-25 09:04:16.138   933   933 I BreventServer: brevent user: 0, uid: 2000
06-25 09:04:16.292   933   933 I BreventServer: core apps: {com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.qualcomm.qti.uceShimService, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, android, com.google.android.grilservice, com.android.ons, org.codeaurora.ims, com.google.android.permissioncontroller, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.inputdevices, com.google.android.dialer, com.android.server.telecom, com.android.proxyhandler, com.google.android.connectivity.resources, com.google.android.documentsui, com.android.settings, com.qualcomm.qti.cne, com.google.android.wifi.resources, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.google.android.inputmethod.latin}
06-25 09:04:16.293   933   933 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, android, com.android.ons, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
06-25 09:04:16.294   933   933 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared, com.google.android.permissioncontroller}
06-25 09:04:16.297   933   933 I BreventServer: installer: com.google.android.packageinstaller
06-25 09:04:16.299   933   933 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
06-25 09:04:16.342   933   951 W BreventServer: ignore overlay package: com.android.systemui(has components)
06-25 09:04:16.345   933   951 W BreventServer: ignore overlay package: com.android.systemui(has components)
06-25 09:04:16.363   933   933 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.google.android.apps.betterbug, com.google.android.youtube, com.bbc.sounds, com.google.android.apps.messaging, com.google.android.apps.safetyhub, com.android.vending, bbc.mobile.news.ww, com.spotify.zerotap, com.instagram.android, com.google.android.gm, com.google.android.carrier, com.google.android.apps.tachyon, mnn.Android, com.apple.android.music, org.thunderdog.challegram, com.google.android.dialer, com.google.android.apps.nbu.files, com.twitter.android, com.google.android.apps.docs, com.google.android.apps.maps, uk.co.bbc.learningenglish, com.pandora.android, com.hbo.hbonow, com.android.chrome, com.skysoft.kkbox.android, com.google.android.videos, com.netflix.mediaclient, com.spotify.music, com.google.android.apps.googlevoice, com.android.imsserviceentitlement, com.adobe.reader, com.google.android.apps.books, com.google.android.apps.tycho, com.google.android.apps.chromecast.app, com.google.android.apps.work.clouddpc, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.google.android.apps.magazines, com.disney.disneyplus}
06-25 09:04:16.380   933   933 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.google.android.apps.subscriptions.red, com.google.android.apps.betterbug, com.google.android.youtube, com.bbc.sounds, com.google.android.googlequicksearchbox, com.google.android.apps.podcasts, com.google.android.apps.messaging, com.google.android.apps.safetyhub, com.android.vending, bbc.mobile.news.ww, com.spotify.zerotap, com.google.android.apps.work.oobconfig, android, com.instagram.android, com.google.android.gm, com.google.android.carrier, com.google.android.apps.tachyon, mnn.Android, com.apple.android.music, org.thunderdog.challegram, com.google.android.dialer, com.google.android.apps.nbu.files, com.google.android.accessibility.soundamplifier, com.twitter.android, com.google.android.apps.docs, com.google.android.apps.maps, uk.co.bbc.learningenglish, com.pandora.android, org.npr.android.news, com.hbo.hbonow, com.google.android.calculator, com.android.chrome, com.google.android.gms, com.google.android.gsf, com.skysoft.kkbox.android, com.google.android.apps.walletnfcrel, com.google.android.videos, com.netflix.mediaclient, com.google.android.apps.photos, com.google.android.calendar, com.spotify.music, com.google.android.apps.googlevoice, com.android.imsserviceentitlement, com.adobe.reader, com.google.android.apps.nbu.paisa.user, com.google.android.wfcactivation, com.google.android.apps.pixelmigrate, com.google.android.apps.books, com.google.android.apps.tycho, com.google.android.apps.chromecast.app, com.google.android.keep, com.google.android.apps.work.clouddpc, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.google.android.play.games, com.google.android.apps.magazines, com.disney.disneyplus}
06-25 09:04:16.380   933   933 I BreventServer: fcm: {com.google.android.apps.betterbug, com.google.android.youtube, com.bbc.sounds, com.google.android.apps.messaging, com.google.android.apps.safetyhub, com.android.vending, bbc.mobile.news.ww, com.spotify.zerotap, com.instagram.android, com.google.android.gm, com.google.android.carrier, com.google.android.apps.tachyon, mnn.Android, com.apple.android.music, org.thunderdog.challegram, com.google.android.dialer, com.google.android.apps.nbu.files, com.twitter.android, com.google.android.apps.docs, com.google.android.apps.maps, uk.co.bbc.learningenglish, com.pandora.android, com.hbo.hbonow, com.android.chrome, com.skysoft.kkbox.android, com.google.android.videos, com.netflix.mediaclient, com.spotify.music, com.google.android.apps.googlevoice, com.android.imsserviceentitlement, com.adobe.reader, com.google.android.apps.books, com.google.android.apps.tycho, com.google.android.apps.chromecast.app, com.google.android.apps.work.clouddpc, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.google.android.apps.magazines, com.disney.disneyplus}
06-25 09:04:16.387   933   933 W BreventServer: Can't getState
06-25 09:04:16.387   933   933 W BreventServer: java.lang.IllegalArgumentException: Unknown package: com.cisco.webex.meetings
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2422)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Parcel.createException(Parcel.java:2402)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Parcel.readException(Parcel.java:2385)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Parcel.readException(Parcel.java:2327)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.content.pm.IPackageManager$Stub$Proxy.getApplicationEnabledSetting(IPackageManager.java:7280)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.HΡP.µHP(:1)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.HPΗ.ΗµH(:1)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.HPΗ.ΡΗH(:18)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.HPΗ.<init>(:64)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.HPΗ.НΡµ(:66)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.PHΗ.HΗ(:5)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:1)
06-25 09:04:16.387   933   933 W BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.PHΗ.do(:14)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.PHΗ.HΡ(:7)
06-25 09:04:16.387   933   933 W BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:3)
06-25 09:04:16.387   933   933 W BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-25 09:04:16.387   933   933 W BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
06-25 09:04:16.387   933   933 W BreventServer: Caused by: android.os.RemoteException: Remote stack trace:
06-25 09:04:16.387   933   933 W BreventServer: 	at com.android.server.pm.PackageManagerService.getApplicationEnabledSetting(PackageManagerService.java:23653)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3347)
06-25 09:04:16.387   933   933 W BreventServer: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:7766)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
06-25 09:04:16.387   933   933 W BreventServer: 	at android.os.Binder.execTransact(Binder.java:1143)
06-25 09:04:16.387   933   933 W BreventServer: 
06-25 09:04:16.387   933   933 W BreventServer: ignore invalid brevented app: com.cisco.webex.meetings
06-25 09:04:16.396   933   933 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 53
06-25 09:04:16.413   933   933 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
06-25 09:04:16.414   933   933 I BreventServer: disabling: {}
06-25 09:04:16.416   933   933 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 18
06-25 09:04:16.417   933   933 I BreventServer: ppid: 872
06-25 09:04:16.417   933   933 I BreventServer: checking standby, sdk: 30
06-25 09:04:16.423   933   933 I BreventServer: init widgets
06-25 09:04:16.431   933   933 W BreventServer: no widgets
06-25 09:04:16.431   933   933 I BreventServer: init notifications
06-25 09:04:16.448   933   933 I BreventServer: recents package name: com.google.android.apps.nexuslauncher
06-25 09:04:16.470   933   956 I BreventServer: system_server: 1950
06-25 09:04:16.470   933   933 I BreventServer: use com.google.android.uvexposurereporter to check upgrade and disable
06-25 09:04:16.470   933   956 I BreventServer: system_server: 1950, now: 1624626256
06-25 09:04:16.475   933   933 I BreventServer: update com.google.android.uvexposurereporter to disabled-user, new state: disabled-user
06-25 09:04:16.483   933   933 I BreventServer: update com.google.android.uvexposurereporter to enabled, new state: enabled
06-25 09:04:16.519   933   933 I BreventServer: use com.google.android.apps.betterbug to check suspend
06-25 09:04:16.521   933   933 I BreventServer: package com.google.android.apps.betterbug suspended state: true
06-25 09:04:16.523   933   933 I BreventServer: package com.google.android.apps.betterbug suspended state: false
06-25 09:04:16.525   933   933 I BreventServer: uid: 10248
06-25 09:04:16.526   933   933 I BreventServer: registerProcessObserver
06-25 09:04:16.528   933   933 I BreventServer: registerUidObserver
06-25 09:04:16.529   933   933 I BreventServer: support standby: true
06-25 09:04:16.529   933   933 I BreventServer: support stopped: true
06-25 09:04:16.529   933   933 I BreventServer: support upgrade: checking
06-25 09:04:16.529   933   933 I BreventServer: support appops: true
06-25 09:04:16.529   933   933 I BreventServer: support disable: true
06-25 09:04:16.530   933   933 I BreventServer: support suspend: true
06-25 09:04:16.530   933   933 I BreventServer: Brevent Server 4.2.6 started
06-25 09:04:16.537   933   956 I BreventServer: support upgrade: true
06-25 09:04:16.575   933   961 I BreventServer: sent binder, message: started
06-25 09:04:16.575   933   933 I BreventServer: binder sent: true
06-25 09:04:16.575   872   872 I BreventLoader: received signal: 10, ppid: 867
06-25 09:04:16.576   867   867 I BreventLoader: check received signal: 10, ppid: 32608
06-25 09:04:16.576   933   933 I BreventServer: sent 10 to 872
06-25 09:04:16.766   933   933 I BreventServer: brevent disabled packages: {}
06-25 09:04:16.800   933   948 I BreventServer: has notification event, use dump to check notification
06-25 09:04:16.808   933   933 I BreventServer: charging wattage: 15
06-25 09:04:16.816   933   933 I BreventServer: battery time: -1
06-25 09:04:16.818   933   933 I BreventServer: charge time: 1675000
06-25 09:04:16.819   933   933 I BreventServer: received first event
06-25 09:04:16.879   933  1000 W BreventServer: cannot decode UNKNOWN as long
06-25 09:04:16.905   933   948 W BreventServer: cannot parse wallpaper
06-25 09:04:17.120   933  1091 W BreventServer: cannot decode UNKNOWN as long
06-25 09:04:17.389   933   933 I BreventServer: check and brevent
06-25 09:04:17.433   872   872 I BreventLoader: worker 933 was ok, exited on signal 9, will try again
06-25 09:04:17.433   872   872 I BreventLoader: signal arrived, update: 1
06-25 09:04:17.433   872   872 I BreventLoader: will start worker in 8 seconds
--- brevent end ---
```
</details><br/>

**Comment by liudongmiao** [comment]
Just update Pixel 3 to SPB2.210513.011, cannot reproduce.

And I don't think the api is changed.

**Comment by liudongmiao** [comment]
Just find and solve in alpha version:

https://jianyu.io/br/alpha/

**Comment by vvb2060** [comment]
https://cs.android.com/android/_/android/platform/frameworks/base/+/d4de97915b932efa3ae309e8adf7864d845884b7 
Android 12的API变化，已修复
