### ISSUE TITLE
f363b52 无法使用root开启服务

### ISSUE THREAD

**Issue by YumeMichi** [brevent/Brevent#74]
OnePlus:/ # sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking for server...fail
[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-muwam_VX-T-iDAYiucavqA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-01 12:33:48.000' -d
09-01 12:33:50.478 10648 10648 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
09-01 12:33:50.478 10648 10648 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
09-01 12:33:50.478 10648 10648 E AndroidRuntime: 	at android.os.Environment.getExternalStorageDirectory(Environment.java:457)
09-01 12:33:50.478 10648 10648 E AndroidRuntime: 	at me.piebridge.brevent.server.f.d(ServerLog.java:83)
09-01 12:33:50.478 10648 10648 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2545)
09-01 12:33:50.478 10648 10648 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-01 12:33:50.478 10648 10648 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: Error reporting crash
09-01 12:33:50.480 10648 10648 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.os.BinderProxy.transact(Binder.java:748)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:123)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:56)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4207)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4205)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:34)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4200)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
09-01 12:33:50.480 10648 10648 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-01 12:33:48.000' -d -s BreventLoader BreventServer
09-01 12:33:49.636 10631 10631 D BreventLoader: line: package:/data/app/me.piebridge.brevent-muwam_VX-T-iDAYiucavqA==/base.apk
09-01 12:33:49.636 10631 10631 D BreventLoader: 
09-01 12:33:49.657 10631 10631 D BreventLoader: loader path: /data/app/me.piebridge.brevent-muwam_VX-T-iDAYiucavqA==/base.apk
09-01 12:33:50.509 10631 10631 E BreventLoader: worker 10648 exited on signal 9
09-01 12:33:50.509 10631 10631 D BreventLoader: signal arrived, update: 0
09-01 12:33:50.511 10627 10627 D BreventLoader: worker 10631 exited with status 0
--- brevent end ---
```

**Comment by liudongmiao** [comment]
这就很尴尬了，root 下的问题：getExternalStorageDirectory。

**Comment by YumeMichi** [comment]
但是没有root又执行不了那个脚本=。=

**Comment by YumeMichi** [comment]
好吧 原本**未取得 root 权限**情况下直接执行 adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh 会提示没有权限，我又试了一下先 adb shell 进去，再执行 sh /data/data/me.piebridge.brevent/brevent.sh 就可以了

**Comment by vvb2060** [comment]
@YumeMichi 你是误打误撞啊。第一次提示没有权限是因为还没等黑域提示“请启动服务”就执行命令，第二次时文件已经生成，所以可以了。
这是一个ROOT启动的问题，在手机上可以先通过网络adb来启动服务。对于Android O，启动后不要关掉网络adb，否则失效。

**Comment by liudongmiao** [comment]
已经在酷安发布 2.1.6o+11，修复了这个问题。
