### ISSUE TITLE
OnePlus9Pro

### ISSUE THREAD

**Issue by l56105878** [brevent/Brevent#743]
OnePlus/OnePlus9Pro_CH/OnePlus9Pro:12/SKQ1.210216.001/R.202111222259:user/release-keys

WARNING: run as root is experimental!!!
checking for server..started, pid: 17173
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/~~4i06T5JkNnH-zhkDJt0QzA==/me.piebridge.brevent-tFBLxLuro8ZkhvpZ9bCanA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '11-28 23:35:55.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '11-28 23:35:55.000' -d -s BreventLoader BreventServer
--------- beginning of main
11-28 23:35:55.316 17166 17166 I BreventLoader: sdk: 31
11-28 23:35:55.548 17173 17173 I BreventServer: args: [10, me.piebridge.brevent, 1638113755, false]
11-28 23:35:55.572 17173 17173 I BreventServer: server log name: server.20211128.2335.17173.txt
11-28 23:35:55.573 17173 17173 I BreventServer: starting Brevent Server 4.2.10
11-28 23:35:55.615 17173 17173 I BreventServer: app_suspended_default_message, orig: %1$s目前无法使用。该应用是由%2$s所管理。, now: %1$s目前无法使用。该应用是由黑阈所管理。
11-28 23:35:55.615 17173 17173 I BreventServer: brevent version: 4.2.10
11-28 23:35:55.618 17173 17173 I BreventServer: add sigcont handler
11-28 23:35:55.620 17173 17173 I BreventServer: sdk: 31, genuine: 0
11-28 23:35:55.621 17173 17173 I BreventServer: brevent user: 0, uid: 2000
11-28 23:35:55.774 17173 17173 I BreventServer: core apps: {com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.qualcomm.qti.uceShimService, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, com.oplus.nhs, com.oplus.exserviceui, android.overlay.common, com.wapi.wapicertmanage, com.oplus.wifisecuredetect, android, com.android.ons, org.codeaurora.ims, com.qualcomm.qti.dynamicddsservice, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.phone.overlay.oplus, oplus, com.google.android.networkstack, com.android.server.telecom, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.packageinstaller, com.qualcomm.qti.devicestatisticsservice, com.android.proxyhandler, com.oplus.appplatform, com.google.android.connectivity.resources, com.google.android.documentsui, com.google.android.permissioncontroller.overlay.oplus, com.oplus.exsystemservice, com.oplus.wallpapers, com.google.android.networkstack.permissionconfig, com.android.settings, com.qualcomm.qti.cne, com.android.phone, com.android.shell, com.qualcomm.qti.seccamservice, com.android.location.fused, com.android.systemui, com.qualcomm.qti.poweroffalarm, com.qti.phone, com.android.permissioncontroller, vendor.qti.imsrcs, com.oplus.screenshot, com.oplus.subsys}
11-28 23:35:55.775 17173 17173 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, android, com.android.ons, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.phone.overlay.oplus, com.android.server.telecom, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.packageinstaller, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.android.permissioncontroller}
11-28 23:35:55.776 17173 17173 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared}
11-28 23:35:55.778 17173 17173 I BreventServer: installer: com.android.packageinstaller
11-28 23:35:55.787 17173 17173 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
11-28 23:35:55.894 17173 17173 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.twitter.android, com.taobao.idlefish, com.alibaba.android.rimet}
11-28 23:35:55.895 17173 17173 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, android, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.google.android.accessibility.soundamplifier, com.twitter.android, com.google.android.gms, com.google.android.gsf, com.taobao.idlefish, com.alibaba.android.rimet, com.google.android.play.games}
11-28 23:35:55.895 17173 17173 I BreventServer: fcm: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.twitter.android, com.taobao.idlefish, com.alibaba.android.rimet}
11-28 23:35:55.909 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 128
11-28 23:35:55.926 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
11-28 23:35:55.926 17173 17173 I BreventServer: disabling: {}
11-28 23:35:55.926 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 13
11-28 23:35:55.927 17173 17173 I BreventServer: ppid: 17168
11-28 23:35:55.927 17173 17173 I BreventServer: checking standby, sdk: 31
11-28 23:35:55.930 17173 17173 I BreventServer: init widgets
11-28 23:35:55.940 17173 17173 I BreventServer: init notifications
11-28 23:35:55.947 17173 17173 I BreventServer: recents package name: com.android.launcher
11-28 23:35:55.967 17173 17173 W BreventServer: Can't set appops(uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.)
11-28 23:35:55.967 17173 17173 I BreventServer: use android.frameworkres.overlay to check upgrade and disable
11-28 23:35:55.969 17173 17173 I BreventServer: update android.frameworkres.overlay to disabled-user, new state: disabled-user
11-28 23:35:55.970 17173 17173 I BreventServer: update android.frameworkres.overlay to enabled, new state: enabled
11-28 23:35:55.977 17173 17193 I BreventServer: system_server: 1500
11-28 23:35:55.977 17173 17193 I BreventServer: system_server: 1500, now: 1638113755
11-28 23:35:55.992 17173 17173 I BreventServer: use com.heytap.music to check suspend
11-28 23:35:55.993 17173 17173 I BreventServer: package com.heytap.music suspended state: true
11-28 23:35:56.010 17173 17173 I BreventServer: package com.heytap.music suspended state: false
11-28 23:35:56.011 17173 17173 W BreventServer: Can't grant permission(grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.)
11-28 23:35:56.012 17173 17173 I BreventServer: uid: 10448
11-28 23:35:56.014 17173 17173 I BreventServer: registerProcessObserver
11-28 23:35:56.016 17173 17173 I BreventServer: registerUidObserver
11-28 23:35:56.016 17173 17173 I BreventServer: support standby: true
11-28 23:35:56.016 17173 17173 I BreventServer: support stopped: true
11-28 23:35:56.016 17173 17173 I BreventServer: support upgrade: checking
11-28 23:35:56.016 17173 17173 I BreventServer: support appops: false
11-28 23:35:56.017 17173 17173 I BreventServer: support disable: true
11-28 23:35:56.017 17173 17173 I BreventServer: support suspend: true
11-28 23:35:56.017 17173 17173 I BreventServer: Brevent Server 4.2.10 started
11-28 23:35:56.025 17173 17193 I BreventServer: support upgrade: true
11-28 23:35:56.089 17173 17197 I BreventServer: sent binder, message: started
11-28 23:35:56.090 17173 17173 I BreventServer: binder sent: true
11-28 23:35:56.090 17173 17173 I BreventServer: sent 10 to 17168
11-28 23:35:56.130 17173 17173 I BreventServer: brevent disabled packages: {}
11-28 23:35:56.139 17173 17186 W BreventServer: no enqueue event, use dump to check notification
11-28 23:35:56.149 17173 17173 E BreventServer: Can't start Brevent: null
11-28 23:35:56.149 17173 17173 E BreventServer: java.lang.NullPointerException
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2447)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.createException(Parcel.java:2425)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2408)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2350)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.app.IAppOpsService$Stub$Proxy.reportRuntimeAppOpAccessMessageAndGetConfig(IAppOpsService.java:1666)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager$1.reportStackTraceIfNeeded(AppOpsManager.java:290)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager$1.onNoted(AppOpsManager.java:265)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager.readAndLogNotedAppops(AppOpsManager.java:9359)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readExceptionCode(Parcel.java:2372)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2347)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.usage.IUsageStatsManager$Stub$Proxy.isAppInactive(IUsageStatsManager.java:1016)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.usage.UsageStatsManager.isAppInactive(UsageStatsManager.java:637)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.μHΗ(:5)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.ΡHН(:1)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.HН(:7)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.Pµ(:4)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.НΡµ(:98)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.Hμ(:5)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:1)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.if(:14)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.HН(:11)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:2)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above
OnePlus/OnePlus9Pro_CH/OnePlus9Pro:12/SKQ1.210216.001/R.202111222259:user/release-keys

WARNING: run as root is experimental!!!
checking for server..started, pid: 17173
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/~~4i06T5JkNnH-zhkDJt0QzA==/me.piebridge.brevent-tFBLxLuro8ZkhvpZ9bCanA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '11-28 23:35:55.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '11-28 23:35:55.000' -d -s BreventLoader BreventServer
--------- beginning of main
11-28 23:35:55.316 17166 17166 I BreventLoader: sdk: 31
11-28 23:35:55.548 17173 17173 I BreventServer: args: [10, me.piebridge.brevent, 1638113755, false]
11-28 23:35:55.572 17173 17173 I BreventServer: server log name: server.20211128.2335.17173.txt
11-28 23:35:55.573 17173 17173 I BreventServer: starting Brevent Server 4.2.10
11-28 23:35:55.615 17173 17173 I BreventServer: app_suspended_default_message, orig: %1$s目前无法使用。该应用是由%2$s所管理。, now: %1$s目前无法使用。该应用是由黑阈所管理。
11-28 23:35:55.615 17173 17173 I BreventServer: brevent version: 4.2.10
11-28 23:35:55.618 17173 17173 I BreventServer: add sigcont handler
11-28 23:35:55.620 17173 17173 I BreventServer: sdk: 31, genuine: 0
11-28 23:35:55.621 17173 17173 I BreventServer: brevent user: 0, uid: 2000
11-28 23:35:55.774 17173 17173 I BreventServer: core apps: {com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.qualcomm.qti.uceShimService, com.android.mms.service, vendor.qti.hardware.cacert.server, com.qualcomm.qti.telephonyservice, com.oplus.nhs, com.oplus.exserviceui, android.overlay.common, com.wapi.wapicertmanage, com.oplus.wifisecuredetect, android, com.android.ons, org.codeaurora.ims, com.qualcomm.qti.dynamicddsservice, com.qualcomm.qcrilmsgtunnel, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.phone.overlay.oplus, oplus, com.google.android.networkstack, com.android.server.telecom, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.packageinstaller, com.qualcomm.qti.devicestatisticsservice, com.android.proxyhandler, com.oplus.appplatform, com.google.android.connectivity.resources, com.google.android.documentsui, com.google.android.permissioncontroller.overlay.oplus, com.oplus.exsystemservice, com.oplus.wallpapers, com.google.android.networkstack.permissionconfig, com.android.settings, com.qualcomm.qti.cne, com.android.phone, com.android.shell, com.qualcomm.qti.seccamservice, com.android.location.fused, com.android.systemui, com.qualcomm.qti.poweroffalarm, com.qti.phone, com.android.permissioncontroller, vendor.qti.imsrcs, com.oplus.screenshot, com.oplus.subsys}
11-28 23:35:55.775 17173 17173 I BreventServer: important core apps: {com.android.providers.telephony, com.android.mms.service, android, com.android.ons, com.android.providers.settings, com.android.wifi.resources.overlay.common, com.android.incallui, com.android.inputdevices, com.android.phone.overlay.oplus, com.android.server.telecom, com.android.wifi.resources, com.android.phone.overlay.common, com.android.systemui.overlay.common, com.android.server.telecom.overlay.common, com.android.packageinstaller, com.android.proxyhandler, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.android.permissioncontroller}
11-28 23:35:55.776 17173 17173 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared}
11-28 23:35:55.778 17173 17173 I BreventServer: installer: com.android.packageinstaller
11-28 23:35:55.787 17173 17173 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
11-28 23:35:55.894 17173 17173 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.twitter.android, com.taobao.idlefish, com.alibaba.android.rimet}
11-28 23:35:55.895 17173 17173 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, android, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.google.android.accessibility.soundamplifier, com.twitter.android, com.google.android.gms, com.google.android.gsf, com.taobao.idlefish, com.alibaba.android.rimet, com.google.android.play.games}
11-28 23:35:55.895 17173 17173 I BreventServer: fcm: {com.google.android.youtube, com.sony.songpal.mdr, org.telegram.messenger, com.youku.phone, com.mt.mtxx.mtxx, com.paypal.android.p2pmobile, com.heytap.health, com.android.vending, com.xxwolo.cc5, com.tencent.mm, com.reddit.frontpage, com.instagram.android, com.microsoft.emmx, com.supercell.clashofclans, com.meitu.meiyancamera, com.twitter.android, com.taobao.idlefish, com.alibaba.android.rimet}
11-28 23:35:55.909 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 128
11-28 23:35:55.926 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
11-28 23:35:55.926 17173 17173 I BreventServer: disabling: {}
11-28 23:35:55.926 17173 17173 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 13
11-28 23:35:55.927 17173 17173 I BreventServer: ppid: 17168
11-28 23:35:55.927 17173 17173 I BreventServer: checking standby, sdk: 31
11-28 23:35:55.930 17173 17173 I BreventServer: init widgets
11-28 23:35:55.940 17173 17173 I BreventServer: init notifications
11-28 23:35:55.947 17173 17173 I BreventServer: recents package name: com.android.launcher
11-28 23:35:55.967 17173 17173 W BreventServer: Can't set appops(uid 2000 does not have android.permission.MANAGE_APP_OPS_MODES.)
11-28 23:35:55.967 17173 17173 I BreventServer: use android.frameworkres.overlay to check upgrade and disable
11-28 23:35:55.969 17173 17173 I BreventServer: update android.frameworkres.overlay to disabled-user, new state: disabled-user
11-28 23:35:55.970 17173 17173 I BreventServer: update android.frameworkres.overlay to enabled, new state: enabled
11-28 23:35:55.977 17173 17193 I BreventServer: system_server: 1500
11-28 23:35:55.977 17173 17193 I BreventServer: system_server: 1500, now: 1638113755
11-28 23:35:55.992 17173 17173 I BreventServer: use com.heytap.music to check suspend
11-28 23:35:55.993 17173 17173 I BreventServer: package com.heytap.music suspended state: true
11-28 23:35:56.010 17173 17173 I BreventServer: package com.heytap.music suspended state: false
11-28 23:35:56.011 17173 17173 W BreventServer: Can't grant permission(grantRuntimePermission: Neither user 2000 nor current process has android.permission.GRANT_RUNTIME_PERMISSIONS.)
11-28 23:35:56.012 17173 17173 I BreventServer: uid: 10448
11-28 23:35:56.014 17173 17173 I BreventServer: registerProcessObserver
11-28 23:35:56.016 17173 17173 I BreventServer: registerUidObserver
11-28 23:35:56.016 17173 17173 I BreventServer: support standby: true
11-28 23:35:56.016 17173 17173 I BreventServer: support stopped: true
11-28 23:35:56.016 17173 17173 I BreventServer: support upgrade: checking
11-28 23:35:56.016 17173 17173 I BreventServer: support appops: false
11-28 23:35:56.017 17173 17173 I BreventServer: support disable: true
11-28 23:35:56.017 17173 17173 I BreventServer: support suspend: true
11-28 23:35:56.017 17173 17173 I BreventServer: Brevent Server 4.2.10 started
11-28 23:35:56.025 17173 17193 I BreventServer: support upgrade: true
11-28 23:35:56.089 17173 17197 I BreventServer: sent binder, message: started
11-28 23:35:56.090 17173 17173 I BreventServer: binder sent: true
11-28 23:35:56.090 17173 17173 I BreventServer: sent 10 to 17168
11-28 23:35:56.130 17173 17173 I BreventServer: brevent disabled packages: {}
11-28 23:35:56.139 17173 17186 W BreventServer: no enqueue event, use dump to check notification
11-28 23:35:56.149 17173 17173 E BreventServer: Can't start Brevent: null
11-28 23:35:56.149 17173 17173 E BreventServer: java.lang.NullPointerException
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2447)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.createException(Parcel.java:2425)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2408)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2350)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.app.IAppOpsService$Stub$Proxy.reportRuntimeAppOpAccessMessageAndGetConfig(IAppOpsService.java:1666)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager$1.reportStackTraceIfNeeded(AppOpsManager.java:290)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager$1.onNoted(AppOpsManager.java:265)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.AppOpsManager.readAndLogNotedAppops(AppOpsManager.java:9359)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readExceptionCode(Parcel.java:2372)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.os.Parcel.readException(Parcel.java:2347)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.usage.IUsageStatsManager$Stub$Proxy.isAppInactive(IUsageStatsManager.java:1016)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at android.app.usage.UsageStatsManager.isAppInactive(UsageStatsManager.java:637)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.μHΗ(:5)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.ΡHН(:1)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.HН(:7)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.Pµ(:4)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.HPΗ.НΡµ(:98)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.Hμ(:5)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:1)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at java.lang.reflect.Method.invoke(Native Method)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.if(:14)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.PHΗ.HН(:11)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at me.piebridge.brevent.server.BreventServer.main(:2)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
11-28 23:35:56.149 17173 17173 E BreventServer: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by vvb2060** [comment]
https://github.com/brevent/Brevent/issues/738#issuecomment-980537967

**Comment by liudongmiao** [comment]
duplicate #738
