### ISSUE TITLE
ANDROID 13 B3无法激活

### ISSUE THREAD

**Issue by cym422948** [brevent/Brevent#770]
This log from my pixel 5A 
Android Version:13(tpb3.220513.017)
`google/barbet/barbet:13/TPB3.220513.017/8678579:user/release-keys

Killed 
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/~~QGbhm9p1OogJ7SV7w4ztjA==/me.piebridge.brevent-sRvZuemheTVNY2TNCnmIUA==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '06-09 15:06:52.000' -d
--------- beginning of crash
06-09 15:06:52.791 17577 17577 E AndroidRuntime: FATAL EXCEPTION: main
06-09 15:06:52.791 17577 17577 E AndroidRuntime: PID: 17577
06-09 15:06:52.791 17577 17577 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at me.piebridge.brevent.server.HΡP.μP(:3)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at me.piebridge.brevent.server.PHΗ.do(:1)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at me.piebridge.brevent.server.PHΗ.HН(:4)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at me.piebridge.brevent.server.BreventServer.main(:2)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
06-09 15:06:52.791 17577 17577 E AndroidRuntime: Error reporting crash
06-09 15:06:52.791 17577 17577 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.BinderProxy.transactNative(Native Method)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.BinderProxy.transact(BinderProxy.java:584)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.os.ServiceManager.getService(ServiceManager.java:147)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.app.ActivityManager$1.create(ActivityManager.java:4688)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.app.ActivityManager$1.create(ActivityManager.java:4685)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.util.Singleton.get(Singleton.java:43)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at android.app.ActivityManager.getService(ActivityManager.java:4676)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-09 15:06:52.791 17577 17577 E AndroidRuntime:  at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
06-09 15:06:53.118 17605 17605 E AndroidRuntime: FATAL EXCEPTION: main
06-09 15:06:53.118 17605 17605 E AndroidRuntime: PID: 17605
06-09 15:06:53.118 17605 17605 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at me.piebridge.brevent.server.HΡP.μP(:3)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at me.piebridge.brevent.server.PHΗ.if(:3)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at me.piebridge.brevent.server.PHΗ.HН(:11)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at me.piebridge.brevent.server.BreventServer.main(:2)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-09 15:06:53.118 17605 17605 E AndroidRuntime:  at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
06-09 15:06:53.119 17605 17605 E AndroidRuntime: Error reporting crash
06-09 15:06:53.119 17605 17605 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.BinderProxy.transactNative(Native Method)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.BinderProxy.transact(BinderProxy.java:584)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.os.ServiceManager.getService(ServiceManager.java:147)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.app.ActivityManager$1.create(ActivityManager.java:4688)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.app.ActivityManager$1.create(ActivityManager.java:4685)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.util.Singleton.get(Singleton.java:43)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at android.app.ActivityManager.getService(ActivityManager.java:4676)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-09 15:06:53.119 17605 17605 E AndroidRuntime:  at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-09 15:06:52.000' -d -s BreventLoader BreventServer
--------- beginning of main
06-09 15:06:52.835 17598 17598 I BreventLoader: sdk: 33
06-09 15:06:52.849 17600 17600 I BreventLoader: pm path me.piebridge.brevent
06-09 15:06:52.876 17600 17600 I BreventLoader: line: package:/data/app/~~QGbhm9p1OogJ7SV7w4ztjA==/me.piebridge.brevent-sRvZuemheTVNY2TNCnmIUA==/base.apk
06-09 15:06:52.878 17600 17600 I BreventLoader: loader path: /data/app/~~QGbhm9p1OogJ7SV7w4ztjA==/me.piebridge.brevent-sRvZuemheTVNY2TNCnmIUA==/base.apk
06-09 15:06:52.880 17605 17605 I BreventLoader: start: 1654758412
06-09 15:06:53.114 17605 17605 I BreventServer: args: [10, me.piebridge.brevent, 1654758412, true]
06-09 15:06:53.129 17600 17600 E BreventLoader: worker 17605 was ko, exited on signal 9
06-09 15:06:53.129 17600 17600 I BreventLoader: signal arrived, update: 0
06-09 15:06:53.130 17598 17598 I BreventLoader: worker 17600 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above`

**Comment by liudongmiao** [comment]
update to latest Beta, Brevent 4.2.15+ or later.

**Comment by cym422948** [comment]
> update to latest Beta, Brevent 4.2.15+ or later.

solved ,I try to update the last beta ,it seems google fixed it
