### ISSUE TITLE
It's crashing when I updated the Android 13 Bata Program version 13 (TPB3.220513.017)

### ISSUE THREAD

**Issue by nok-HuUhfA1ApIsP** [brevent/Brevent#771]
as title

logs:

google/flame/flame:13/TPB3.220513.017/8678579:user/release-keys

Killed 
chmod: chmod '/data/local/tmp/brevent' to 0755: Operation not permitted
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/~~X_4Fv1BT0YlAjrSeTMmi1w==/me.piebridge.brevent-OgG4Hph3IGz_AweP63Zutw==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '06-09 20:43:24.000' -d
--------- beginning of crash
06-09 20:43:24.663 31898 31898 E AndroidRuntime: FATAL EXCEPTION: main
06-09 20:43:24.663 31898 31898 E AndroidRuntime: PID: 31898
06-09 20:43:24.663 31898 31898 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at me.piebridge.brevent.server.HΡP.μP(:3)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.do(:1)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.HН(:4)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-09 20:43:24.663 31898 31898 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: Error reporting crash
06-09 20:43:24.664 31898 31898 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4688)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4685)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4676)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-09 20:43:24.664 31898 31898 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: FATAL EXCEPTION: main
06-09 20:43:25.014 31953 31953 E AndroidRuntime: PID: 31953
06-09 20:43:25.014 31953 31953 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at me.piebridge.brevent.server.HΡP.μP(:3)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.if(:3)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.HН(:11)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-09 20:43:25.014 31953 31953 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: Error reporting crash
06-09 20:43:25.015 31953 31953 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4688)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4685)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4676)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
06-09 20:43:25.015 31953 31953 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '06-09 20:43:24.000' -d -s BreventLoader BreventServer
--------- beginning of main
06-09 20:43:24.707 31946 31946 I BreventLoader: sdk: 33
06-09 20:43:24.728 31948 31948 I BreventLoader: pm path me.piebridge.brevent
06-09 20:43:24.753 31948 31948 I BreventLoader: line: package:/data/app/~~X_4Fv1BT0YlAjrSeTMmi1w==/me.piebridge.brevent-OgG4Hph3IGz_AweP63Zutw==/base.apk
06-09 20:43:24.756 31948 31948 I BreventLoader: loader path: /data/app/~~X_4Fv1BT0YlAjrSeTMmi1w==/me.piebridge.brevent-OgG4Hph3IGz_AweP63Zutw==/base.apk
06-09 20:43:24.757 31953 31953 I BreventLoader: start: 1654778604
06-09 20:43:25.011 31953 31953 I BreventServer: args: [10, me.piebridge.brevent, 1654778604, true]
06-09 20:43:25.035 31948 31948 E BreventLoader: worker 31953 was ko, exited on signal 9
06-09 20:43:25.035 31948 31948 I BreventLoader: signal arrived, update: 0
06-09 20:43:25.035 31946 31946 I BreventLoader: worker 31948 exited with status 0
--- brevent end ---
```
</details><br/>

**Comment by liudongmiao** [comment]
update to latest Beta.
In Android 13 Beta, it's marked as REL, and Brevent cannot recognize it as Android 13 Beta.
