### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by Lam17** [brevent/Brevent#805]
<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '03-13 17:52:03.000' -d
--------- beginning of crash
03-13 17:52:03.308 23214 23214 E AndroidRuntime: FATAL EXCEPTION: main
03-13 17:52:03.308 23214 23214 E AndroidRuntime: PID: 23214
03-13 17:52:03.308 23214 23214 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at me.piebridge.brevent.server.HΡP.μP(:3)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.if(:3)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.HН(:11)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:391)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: Error reporting crash
03-13 17:52:03.308 23214 23214 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:672)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:372)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4688)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.app.ActivityManager$1.create(ActivityManager.java:4685)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:4676)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:187)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
03-13 17:52:03.308 23214 23214 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '03-13 17:52:03.000' -d -s BreventLoader BreventServer
--------- beginning of main
03-13 17:52:03.019 23205 23205 I BreventLoader: sdk: 33
03-13 17:52:03.036 23209 23209 I BreventLoader: pm path me.piebridge.brevent
03-13 17:52:03.085 23209 23209 I BreventLoader: line: package:/data/app/~~pZ10ds6aG2Q7t6SknROTRg==/me.piebridge.brevent-RoRCE4N19_a2sx-mGn23TQ==/base.apk
03-13 17:52:03.088 23209 23209 I BreventLoader: loader path: /data/app/~~pZ10ds6aG2Q7t6SknROTRg==/me.piebridge.brevent-RoRCE4N19_a2sx-mGn23TQ==/base.apk
03-13 17:52:03.094 23214 23214 I BreventLoader: start: 1678701123
03-13 17:52:03.299 23214 23214 I BreventServer: args: [10, me.piebridge.brevent, 1678701123, true]
03-13 17:52:03.348 23209 23209 E BreventLoader: worker 23214 was ko, exited on signal 9
03-13 17:52:03.348 23209 23209 I BreventLoader: signal arrived, update: 0
03-13 17:52:03.350 23205 23205 I BreventLoader: worker 23209 exited with status 0
--- brevent end ---
```
</details><br/>

environment：
[ro.product.build.version.release]: [13]
[ro.product.build.version.release_or_codename]: [13]
[ro.product.build.version.sdk]: [33]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cuptsm]: [ONEPLUS|ESE|01|02]
[ro.product.device]: [OnePlus8Pro]
[ro.product.first_api_level]: [29]
[ro.product.hw]: [AE008]
[ro.product.locale]: [zh-CN]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [IN2020]
[ro.product.name]: [OnePlus8Pro_CH]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [OnePlus8Pro]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [IN2020]
[ro.product.odm.name]: [OnePlus8Pro_CH]
[ro.product.oem_dm]: [1]

**Comment by liudongmiao** [comment]
update to latest version
