### ISSUE TITLE
无法启动服务

### ISSUE THREAD

**Issue by cEvolve05** [brevent/Brevent#819]
无论是root还是无线USB调试，连接电脑USB调试都不行
Android 13
Pixel 6 Pro

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '07-23 14:50:33.000' -d
--------- beginning of crash
07-23 14:50:34.496  7748  7769 E AndroidRuntime: FATAL EXCEPTION: binder:7748_1
07-23 14:50:34.496  7748  7769 E AndroidRuntime: PID: 7748
07-23 14:50:34.496  7748  7769 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "void android.content.pm.IOnAppsChangedListener.onPackageLoadingProgressChanged(android.os.UserHandle, java.lang.String, float)"
07-23 14:50:34.496  7748  7769 E AndroidRuntime: 	at android.content.pm.IOnAppsChangedListener$Stub.onTransact(IOnAppsChangedListener.java:235)
07-23 14:50:34.496  7748  7769 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1285)
07-23 14:50:34.496  7748  7769 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1244)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '07-23 14:50:33.000' -d -s BreventLoader BreventServer
--------- beginning of main
07-23 14:50:33.253  7736  7736 I BreventLoader: sdk: 33
07-23 14:50:33.600  7748  7748 I BreventServer: args: [10, me.piebridge.brevent, 1690095033, false]
07-23 14:50:33.623  7748  7748 I BreventServer: server log name: server.20230723.1450.7748.txt
07-23 14:50:33.625  7748  7748 I BreventServer: starting Brevent Server 4.2.19
07-23 14:50:33.658  7748  7748 I BreventServer: app_suspended_default_message, orig: %1$s isn’t available right now. This is managed by %2$s., now: %1$s isn’t available right now. This is managed by Brevent.
07-23 14:50:33.658  7748  7748 I BreventServer: brevent version: 4.2.19
07-23 14:50:33.660  7748  7748 I BreventServer: add sigcont handler
07-23 14:50:33.663  7748  7748 I BreventServer: sdk: 33, genuine: 0
07-23 14:50:33.663  7748  7748 I BreventServer: brevent user: 0, uid: 2000
07-23 14:50:33.821  7748  7748 I BreventServer: core apps: {com.android.uwb.resources, com.google.android.ext.services, com.android.providers.telephony, com.google.android.ext.shared, com.android.mms.service, android, com.google.android.grilservice, com.android.ons, com.google.android.permissioncontroller, com.android.providers.settings, com.google.android.iwlan, com.android.inputdevices, com.google.android.dialer, com.google.android.networkstack, com.android.server.telecom, com.android.proxyhandler, com.google.android.safetycenter.resources, com.android.intentresolver, com.google.android.connectivity.resources, com.google.android.documentsui, com.google.android.apps.cbrsnetworkmonitor, com.android.settings, com.google.android.wifi.resources, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui, com.google.android.inputmethod.latin}
07-23 14:50:33.821  7748  7748 I BreventServer: important core apps: {com.android.uwb.resources, com.android.providers.telephony, com.android.mms.service, android, com.android.ons, com.android.providers.settings, com.android.inputdevices, com.android.server.telecom, com.android.proxyhandler, com.android.intentresolver, com.android.settings, com.android.phone, com.android.shell, com.android.location.fused, com.android.systemui}
07-23 14:50:33.822  7748  7748 I BreventServer: extra important core apps: {com.google.android.ext.services, com.google.android.ext.shared, com.google.android.permissioncontroller}
07-23 14:50:33.825  7748  7748 I BreventServer: installer: com.google.android.packageinstaller
07-23 14:50:33.827  7748  7748 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
07-23 14:50:33.851  7748  7774 W BreventServer: ignore overlay package: com.android.systemui(has components)
07-23 14:50:33.858  7748  7774 W BreventServer: ignore overlay package: com.android.systemui(has components)
07-23 14:50:34.020  7748  7748 I BreventServer: com.google.firebase.MESSAGING_EVENT: {com.google.android.youtube, org.telegram.messenger, com.sololearn, com.google.android.apps.paidtasks, com.microblink.photomath, com.google.android.apps.messaging, com.photomyne, com.discord, com.duolingo, net.tsapps.appsales, com.github.android, com.google.android.apps.safetyhub, com.android.vending, com.idle.pseudo3d.hero, com.tencent.mm, com.reddit.frontpage, com.google.android.apps.work.oobconfig, com.google.android.gm, com.google.android.carrier, com.nianticlabs.pokemongo, com.msd.consumerChinese, com.google.android.dialer, com.google.android.apps.nbu.files, com.mxtech.videoplayer.ad, com.bilibili.app.in, com.twitter.android, com.google.android.apps.maps, com.android.chrome, com.microsoft.office.officehubrow, com.facebook.katana, com.zhihu.android, com.valvesoftware.android.steam.community, fi.reworks.redecor, com.android.imsserviceentitlement, com.innologica.inoreader, com.google.android.wfcactivation, com.google.android.apps.scone, com.google.android.apps.work.clouddpc, com.evozi.network, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.taobao.taobao, com.google.android.apps.magazines, com.google.android.apps.adm, com.google.android.apps.gcs}
07-23 14:50:34.024  7748  7748 I BreventServer: com.google.android.c2dm.intent.RECEIVE: {com.google.android.apps.subscriptions.red, com.google.android.youtube, com.google.android.googlequicksearchbox, org.telegram.messenger, com.sololearn, com.google.android.apps.paidtasks, com.google.android.apps.podcasts, com.microblink.photomath, com.google.android.apps.messaging, com.photomyne, com.discord, com.duolingo, net.tsapps.appsales, com.github.android, com.google.android.apps.safetyhub, com.android.vending, com.idle.pseudo3d.hero, com.tencent.mm, com.reddit.frontpage, com.google.android.apps.work.oobconfig, android, com.google.android.gm, com.google.android.carrier, com.nianticlabs.pokemongo, com.msd.consumerChinese, com.google.android.dialer, com.google.android.apps.nbu.files, com.mxtech.videoplayer.ad, com.bilibili.app.in, com.google.android.apps.village.boond, com.twitter.android, com.evezzon.nightowl, com.google.android.apps.docs, com.google.android.apps.maps, com.google.android.contacts, com.android.chrome, com.google.android.gms, com.google.android.gsf, com.google.android.apps.walletnfcrel, com.google.android.apps.photos, com.google.android.calendar, com.microsoft.office.officehubrow, com.facebook.katana, com.zhihu.android, com.valvesoftware.android.steam.community, fi.reworks.redecor, com.android.imsserviceentitlement, com.innologica.inoreader, com.google.android.apps.nbu.paisa.user, com.google.android.wfcactivation, org.joinmastodon.android, com.google.android.apps.scone, com.google.android.apps.tasks, com.delphicoder.flud, com.google.android.keep, com.google.android.apps.work.clouddpc, com.evozi.network, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.taobao.taobao, com.google.android.play.games, com.google.android.apps.magazines, com.google.android.apps.adm, com.google.android.apps.gcs}
07-23 14:50:34.024  7748  7748 I BreventServer: fcm: {com.google.android.youtube, org.telegram.messenger, com.sololearn, com.google.android.apps.paidtasks, com.microblink.photomath, com.google.android.apps.messaging, com.photomyne, com.discord, com.duolingo, net.tsapps.appsales, com.github.android, com.google.android.apps.safetyhub, com.android.vending, com.idle.pseudo3d.hero, com.tencent.mm, com.reddit.frontpage, com.google.android.apps.work.oobconfig, com.google.android.gm, com.google.android.carrier, com.nianticlabs.pokemongo, com.msd.consumerChinese, com.google.android.dialer, com.google.android.apps.nbu.files, com.mxtech.videoplayer.ad, com.bilibili.app.in, com.twitter.android, com.google.android.apps.maps, com.android.chrome, com.microsoft.office.officehubrow, com.facebook.katana, com.zhihu.android, com.valvesoftware.android.steam.community, fi.reworks.redecor, com.android.imsserviceentitlement, com.innologica.inoreader, com.google.android.wfcactivation, com.google.android.apps.scone, com.google.android.apps.work.clouddpc, com.evozi.network, com.google.android.apps.youtube.music, com.google.android.apps.helprtc, com.taobao.taobao, com.google.android.apps.magazines, com.google.android.apps.adm, com.google.android.apps.gcs}
07-23 14:50:34.028  7748  7748 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 42
07-23 14:50:34.033  7748  7748 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.disabled, size: 0
07-23 14:50:34.033  7748  7748 I BreventServer: disabling: {}
07-23 14:50:34.033  7748  7748 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.appops, size: 24
07-23 14:50:34.033  7748  7748 I BreventServer: ppid: 7743
07-23 14:50:34.033  7748  7748 I BreventServer: checking standby, sdk: 33
07-23 14:50:34.035  7748  7748 I BreventServer: init widgets
07-23 14:50:34.044  7748  7748 W BreventServer: no widgets
07-23 14:50:34.044  7748  7748 I BreventServer: init notifications
07-23 14:50:34.073  7748  7748 I BreventServer: recents package name: com.google.android.apps.nexuslauncher
07-23 14:50:34.097  7748  7780 I BreventServer: system_server: 1623
07-23 14:50:34.097  7748  7780 I BreventServer: system_server: 1623, now: 1690095034
07-23 14:50:34.098  7748  7748 I BreventServer: use com.android.internal.display.cutout.emulation.noCutout to check upgrade and disable
07-23 14:50:34.099  7748  7748 I BreventServer: update com.android.internal.display.cutout.emulation.noCutout to disabled-user, new state: disabled-user
07-23 14:50:34.100  7748  7748 I BreventServer: update com.android.internal.display.cutout.emulation.noCutout to enabled, new state: enabled
07-23 14:50:34.106  7748  7748 I BreventServer: use com.google.android.overlay.trafficlightfaceoverlay to check suspend
07-23 14:50:34.129  7748  7748 I BreventServer: package com.google.android.overlay.trafficlightfaceoverlay suspended state: true
07-23 14:50:34.131  7748  7748 I BreventServer: package com.google.android.overlay.trafficlightfaceoverlay suspended state: false
07-23 14:50:34.154  7748  7748 I BreventServer: uid: 10358
07-23 14:50:34.156  7748  7748 I BreventServer: registerProcessObserver
07-23 14:50:34.159  7748  7748 I BreventServer: registerUidObserver
07-23 14:50:34.160  7748  7748 I BreventServer: support standby: true
07-23 14:50:34.160  7748  7748 I BreventServer: support stopped: true
07-23 14:50:34.160  7748  7748 I BreventServer: support upgrade: checking
07-23 14:50:34.161  7748  7748 I BreventServer: support appops: true
07-23 14:50:34.161  7748  7748 I BreventServer: support disable: true
07-23 14:50:34.161  7748  7748 I BreventServer: support suspend: true
07-23 14:50:34.161  7748  7748 I BreventServer: Brevent Server 4.2.19 started
07-23 14:50:34.170  7748  7796 I BreventServer: sent binder, message: started
07-23 14:50:34.171  7748  7748 I BreventServer: binder sent: true
07-23 14:50:34.171  7748  7748 I BreventServer: sent 10 to 7743
07-23 14:50:34.206  7748  7780 I BreventServer: support upgrade: true
07-23 14:50:34.470  7748  7748 I BreventServer: brevent disabled packages: {}
07-23 14:50:34.494  7748  7748 I BreventServer: charging wattage: 15
07-23 14:50:34.496  7748  7748 I BreventServer: battery time: -1
07-23 14:50:34.497  7748  7748 I BreventServer: charge time: 2944000
07-23 14:50:34.501  7748  7770 I BreventServer: has notification event, use dump to check notification
--- brevent end ---
```
</details><br/>

**Comment by liudongmiao** [comment]
https://jianyu.io/br/beta/

最新 beta 版，Google 一直审核中。

**Comment by cEvolve05** [comment]
> https://jianyu.io/br/beta/
> 
> 最新 beta 版，Google 一直审核中。

解决了，感谢
