### ISSUE TITLE
无法用root启动

### ISSUE THREAD

**Issue by ted-dev-42** [brevent/Brevent#84]
adb shell启动没问题，root启动没有成功过。
测试环境：
手机：nexus 6P
系统： android 8 (之前7也一样不行)

Log: 

WARNING: run as root is experimental!!!
checking for server..started, pid: 25550
checking for stable..quited

[command] pm path me.piebridge.brevent
package:/data/app/me.piebridge.brevent-ZratenALcnff6WDLkEE3Uw==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '09-07 11:15:35.000' -d
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '09-07 11:15:35.000' -d -s BreventLoader BreventServer
09-07 11:15:36.020 25534 25534 D BreventLoader: line: package:/data/app/me.piebridge.brevent-ZratenALcnff6WDLkEE3Uw==/base.apk
09-07 11:15:36.020 25534 25534 D BreventLoader:
09-07 11:15:36.043 25534 25534 D BreventLoader: loader path: /data/app/me.piebridge.brevent-ZratenALcnff6WDLkEE3Uw==/base.apk
09-07 11:15:36.904 25550 25550 I BreventServer: starting Brevent Server 2.1.7
09-07 11:15:36.934 25550 25550 I BreventServer: brevent user: 0, uid: 0
09-07 11:15:36.936 25550 25550 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
09-07 11:15:36.953 25550 25550 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 45
09-07 11:15:36.966 25550 25550 E BreventServer: Cannot dump appwidget(brevent dumpsys dead)
09-07 11:15:36.966 25550 25550 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
09-07 11:15:36.966 25550 25550 E BreventServer:         at android.os.BinderProxy.transactNative(Native Method)
09-07 11:15:36.966 25550 25550 E BreventServer:         at android.os.BinderProxy.transact(Binder.java:748)
09-07 11:15:36.966 25550 25550 E BreventServer:         at android.os.BinderProxy.dumpAsync(Binder.java:783)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.e.b(HideApi.java:847)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.e.a(HideApi.java:322)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:329)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:2245)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2465)
09-07 11:15:36.966 25550 25550 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
09-07 11:15:36.966 25550 25550 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2567)
09-07 11:15:36.966 25550 25550 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-07 11:15:36.966 25550 25550 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
09-07 11:15:36.967 25550 25550 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/17
09-07 11:15:37.005 25534 25534 E BreventLoader: worker 25550 exited with status 1
09-07 11:15:37.005 25534 25534 D BreventLoader: signal arrived, update: 0
09-07 11:15:37.006 25530 25530 D BreventLoader: worker 25534 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above

**logcat输出的log，比上面多几句：**
```
09-07 11:07:59.527 22808 22808 I BreventServer: starting Brevent Server 2.1.7
09-07 11:07:59.549 22460 22460 W com.youku.phone:phone_monitor: type=1400 audit(0.0:44193): avc: denied { getattr } for comm=4173796E635461736B202336 path="/proc/sysrq-trigger" dev="proc" ino=4026548052 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:proc_sysrq:s0 tclass=file permissive=0
09-07 11:07:59.557 22808 22808 I BreventServer: brevent user: 0, uid: 0
09-07 11:07:59.560 22808 22808 I BreventServer: brevent data directory: /data/user_de/0/com.android.shell
09-07 11:07:59.579 22808 22808 I BreventServer: load /data/user_de/0/com.android.shell/me.piebridge.brevent.list, size: 45
09-07 11:07:59.589 22808 22808 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 28)
09-07 11:07:59.586 22808 22808 W main    : type=1400 audit(0.0:44229): avc: denied { write } for path="pipe:[1693845]" dev="pipefs" ino=1693845 scontext=u:r:system_server:s0 tcontext=u:r:su:s0 tclass=fifo_file permissive=0
09-07 11:07:59.589 22808 22808 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 28)
09-07 11:07:59.591 22808 22808 E BreventServer: Cannot dump appwidget(brevent dumpsys dead)
09-07 11:07:59.591 22808 22808 E BreventServer: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
09-07 11:07:59.591 22808 22808 E BreventServer:         at android.os.BinderProxy.transactNative(Native Method)
09-07 11:07:59.591 22808 22808 E BreventServer:         at android.os.BinderProxy.transact(Binder.java:748)
09-07 11:07:59.591 22808 22808 E BreventServer:         at android.os.BinderProxy.dumpAsync(Binder.java:783)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.e.b(HideApi.java:847)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.e.a(HideApi.java:322)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.BreventServer.<init>(BreventServer.java:329)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.BreventServer.b(BreventServer.java:2245)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.BreventServer.a(BreventServer.java:2465)
09-07 11:07:59.591 22808 22808 E BreventServer:         at java.lang.reflect.Method.invoke(Native Method)
09-07 11:07:59.591 22808 22808 E BreventServer:         at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:2567)
09-07 11:07:59.591 22808 22808 E BreventServer:         at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
09-07 11:07:59.591 22808 22808 E BreventServer:         at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:284)
09-07 11:07:59.592 22808 22808 E BreventServer: for more information, refer https://github.com/brevent/Brevent/issues/17
09-07 11:07:59.593 22808 22808 I brevent_server: System.exit called, status: 1
```

**Comment by vvb2060** [comment]
报错信息中提到了一个网址，就在倒数第二行，麻烦点过去看看。
