### ISSUE TITLE
POCO X4 GT（EEA版）不兼容Brevent

### ISSUE THREAD

**Issue by Leoeis** [brevent/Brevent#859]
错误日志如下
（已赋予root权限）

`PS C:\Users\admin\Desktop\新建文件夹\platform-tools> ./adb -d shell sh /data/data/me.piebridge.brevent/brevent.sh
sh: /data/data/me.piebridge.brevent/brevent.sh: Permission denied
PS C:\Users\admin\Desktop\新建文件夹\platform-tools> adb shell
xaga:/ $ su
xaga:/ # sh /data/data/me.piebridge.brevent/brevent.sh
WARNING: run as root is experimental!!!
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/~~n7Zu3ynk1jrHtFLoGX14LA==/me.piebridge.brevent-lMlLQBe9HyXhfiwavzb3Rg==/base.apk
please report bug to https://github.com/brevent/Brevent/issues with log below
```
--- crash start ---
[command] logcat -b crash -t '02-01 19:16:14.000' -d
--------- beginning of crash
02-01 19:16:15.076  5281  5281 E AndroidRuntime: FATAL EXCEPTION: main
02-01 19:16:15.076  5281  5281 E AndroidRuntime: PID: 5281
02-01 19:16:15.076  5281  5281 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getPackageInfo(Ljava/lang/String;II)Landroid/content/pm/PackageInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
02-01 19:16:15.076  5281  5281 E AndroidRuntime:        at me.piebridge.brevent.server.g.a(HideApi.java:243)
02-01 19:16:15.076  5281  5281 E AndroidRuntime:        at me.piebridge.brevent.server.BreventServer.main(BreventServer.java:34)
02-01 19:16:15.076  5281  5281 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
02-01 19:16:15.076  5281  5281 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:387)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '02-01 19:16:14.000' -d -s BreventLoader BreventServer
--------- beginning of main
02-01 19:16:14.862  5276  5276 I BreventLoader: line: package:/data/app/~~n7Zu3ynk1jrHtFLoGX14LA==/me.piebridge.brevent-lMlLQBe9HyXhfiwavzb3Rg==/base.apk
02-01 19:16:14.866  5276  5276 I BreventLoader: loader path: /data/app/~~n7Zu3ynk1jrHtFLoGX14LA==/me.piebridge.brevent-lMlLQBe9HyXhfiwavzb3Rg==/base.apk
02-01 19:16:14.868  5281  5281 I BreventLoader: start: 1706786174
02-01 19:16:15.105  5276  5276 E BreventLoader: worker 5281 exited on signal 9
02-01 19:16:15.106  5276  5276 I BreventLoader: signal arrived, update: 0
02-01 19:16:15.107  5273  5273 I BreventLoader: worker 5276 exited with status 0
--- brevent end ---
```
please report bug to https://github.com/brevent/Brevent/issues with log above
1|xaga:/ #

`

**Comment by liudongmiao** [comment]
这个 api 自 android 13 更换签名，由于 android 13 已经正式版，所以不会兼容处理。
