### ISSUE TITLE
关于play版的显示支付开关

### ISSUE THREAD

**Issue by CVN-77** [brevent/Brevent#92]
版本是2.1.9c，play商店被黑域且没有允许同步，play处于没有运行，打开黑域里的显示开关后一直在检查结算情况，尚没见到允许30s的情况，本机情况的日志如下

**Comment by CVN-77** [comment]
```
09-12 08:59:44.042 18851 19022 W BreventServer: no tracks
09-12 08:59:52.997 18851 19022 W BreventServer: no tracks
09-12 09:00:00.902 18851 18851 W BreventServer: no tracks
09-12 09:00:01.963 18851 19022 W BreventServer: no tracks
09-12 09:00:09.005 18851 19022 W BreventServer: no tracks
09-12 09:00:13.649 18851 18851 W BreventServer: no tracks
09-12 09:00:20.663 18851 18851 W BreventServer: no tracks
09-12 09:00:45.149 18851 18851 W BreventServer: no tracks
09-12 09:00:49.212 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:00:49.217 11281 11302 V BreventUI: connected, started: true
09-12 09:00:49.217 11281 14149 D BreventUI: request status
09-12 09:00:49.223 11281 11302 V BreventUI: connected, started: true
09-12 09:00:49.342 18851 19022 W BreventServer: no tracks
09-12 09:00:50.153 11281 14149 D BreventUI: received response
09-12 09:00:50.589 11281 14149 D BreventUI: setAlarm
09-12 09:00:50.598 11281 11302 V BreventUI: connected, started: true
09-12 09:00:53.418 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:01:00.733 11281 11281 D BreventUI: activatePlay
09-12 09:01:06.309 11281 11281 D BreventUI: onActivityResult
09-12 09:01:06.314 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:01:06.318 11281 11302 V BreventUI: connected, started: true
09-12 09:01:06.318 11281 14149 D BreventUI: request status
09-12 09:01:06.322 11281 11302 V BreventUI: connected, started: true
09-12 09:01:06.439 18851 19022 W BreventServer: no tracks
09-12 09:01:06.646 11281 11281 D BreventUI: unbindActivateService
09-12 09:01:06.647 11281 11281 D BreventUI: cannot unbind activateConnection
09-12 09:01:06.647 11281 11281 D BreventUI: java.lang.IllegalArgumentException: Service not registered: Handler (me.piebridge.a.a) {f45460c}
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1407)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1657)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at me.piebridge.a.b.A(DonateActivity.java:239)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at me.piebridge.a.b.y(DonateActivity.java:662)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at me.piebridge.a.b.onStop(DonateActivity.java:122)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.Activity.performStop(Activity.java:7108)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4355)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.os.Looper.loop(Looper.java:156)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
09-12 09:01:06.647 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
09-12 09:01:07.408 11281 14149 D BreventUI: setAlarm
09-12 09:01:18.354 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:01:18.361 11281 11302 V BreventUI: connected, started: true
09-12 09:01:18.361 11281 14149 D BreventUI: request status
09-12 09:01:18.384 11281 11302 V BreventUI: connected, started: true
09-12 09:01:18.507 18851 19022 W BreventServer: no tracks
09-12 09:01:19.621 11281 14149 D BreventUI: setAlarm
09-12 09:01:21.453 11281 11281 D BreventUI: activatePlay
09-12 09:01:21.515 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:01:23.969 18851 18851 W BreventServer: no tracks
09-12 09:01:25.784 11281 11281 D BreventUI: unbindActivateService
09-12 09:01:25.789 11281 11281 D BreventUI: cannot unbind activateConnection
09-12 09:01:25.789 11281 11281 D BreventUI: java.lang.IllegalArgumentException: Service not registered: Handler (me.piebridge.a.a) {9d7fd26}
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1407)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1657)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at me.piebridge.a.b.A(DonateActivity.java:239)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at me.piebridge.a.b.y(DonateActivity.java:662)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at me.piebridge.a.b.onStop(DonateActivity.java:122)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.Activity.performStop(Activity.java:7108)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4064)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4117)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ActivityThread.-wrap27(ActivityThread.java)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.os.Looper.loop(Looper.java:156)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
09-12 09:01:25.789 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
09-12 09:02:07.329 11281 11281 D BreventUI: activatePlay
09-12 09:02:07.357 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:02:08.783 11281 11281 D BreventUI: onActivityResult
09-12 09:02:08.786 11281 11281 D BreventUI: current: zh_CN, locale: zh_CN, changed: false
09-12 09:02:08.790 11281 11302 V BreventUI: connected, started: true
09-12 09:02:08.790 11281 14149 D BreventUI: request status
09-12 09:02:08.794 11281 11302 V BreventUI: connected, started: true
09-12 09:02:08.913 18851 19022 W BreventServer: no tracks
09-12 09:02:09.116 11281 11281 D BreventUI: unbindActivateService
09-12 09:02:09.117 11281 11281 D BreventUI: cannot unbind activateConnection
09-12 09:02:09.117 11281 11281 D BreventUI: java.lang.IllegalArgumentException: Service not registered: Handler (me.piebridge.a.a) {8c1a156}
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1407)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1657)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:648)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at me.piebridge.a.b.A(DonateActivity.java:239)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at me.piebridge.a.b.y(DonateActivity.java:662)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at me.piebridge.a.b.onStop(DonateActivity.java:122)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1301)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.Activity.performStop(Activity.java:7108)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4355)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4417)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ActivityThread.-wrap6(ActivityThread.java)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.os.Handler.dispatchMessage(Handler.java:105)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.os.Looper.loop(Looper.java:156)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
09-12 09:02:09.117 11281 11281 D BreventUI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
09-12 09:02:09.805 11281 14149 D BreventUI: setAlarm
09-12 09:02:12.502 11281 14149 D BreventUI: logcat for system.txt
09-12 09:02:12.786 11281 14149 D BreventUI: logcat for events.txt
09-12 09:02:12.904 11281 14149 D BreventUI: logcat for crash.txt
09-12 09:02:12.944 11281 14149 D BreventUI: logcat for brevent.txt
```

**Comment by liudongmiao** [comment]
你得结合 system 日志看这个 service 情况，到底是启来了还是没启来...

**Comment by CVN-77** [comment]
system.txt

system日志有些多…我看了一下感觉service没启…

**Comment by liudongmiao** [comment]
> 09-12 09:02:07.344  1251  2530 W ActivityManager_service: prevent by hsm Will not start service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending } U=0: force null
09-12 09:02:07.344  1251  2530 W ActivityManager: Unable to start service Intent { act=com.android.vending.billing.InAppBillingService.BIND pkg=com.android.vending } U=0: not found

自己去看看这个 hsm 是啥吧...看起来，还是一个系统级的服务。
服务都没启来，所以黑域能检测到才怪。
至于你说的允许同步，黑域额外做了其它的事，停止状态 + 非待机。

**Comment by CVN-77** [comment]
找到了，原来是被自带手机管家的关联启动管理给拦截了…第一次发现emui的阻止关联唤醒也有些智能…
![screenshot_20170913010152](https://user-images.githubusercontent.com/26182187/30339005-2b15d55c-9820-11e7-8407-f70288539ef0.png)

不限制play被黑域唤醒后，2.1.9c确实没问题，有允许30秒。play在停止状态，进入黑域设置能被唤醒，返回后play还是停止；play商店back后被待机时，进入黑域设置也能唤醒，返回后play恢复待机。

**Comment by CVN-77** [comment]
有些尴尬，发现emui允许play被关联启动后，黑域2.1.8的版本也没问题，包括play没有运行时和待机时，都能被黑域显示支付唤醒…

不过也是因为以前默认play不被关联启动，黑域长期检查结算，才看清play版黑域设置里显示支付的提示（允许play关联启动后显示支付几乎是瞬间就刷新，看不清提示…）

现在新版2.1.9c专门更新了提示，优化play加了允许30s，还是挺不错的😄

**Comment by liudongmiao** [comment]
优化 play 等支付是 30 秒，激进模式出来之前，一直是这样...

**Comment by CVN-77** [comment]
确实是，我用回老版本，发现只要允许play被关联启动，支付唤醒也没问题…

主要是以前显示支付没怎么开，一般是关的，就没怎么留意这块，加上自从用了黑域之后，我就很少再动自带的手机管家，把关联启动给忘了…
