### ISSUE TITLE
 💁

### ISSUE THREAD

**Issue by hema203** [brevent/Brevent#953]
Redmi/gust_global/gust:14/UP1A.231005.007/V816.0.2.0.UGPMIXM:user/release-keys

Killed 
checking for server..fail
[command] pm path me.piebridge.brevent
package:/data/app/~~63QwQ1SlhaAG_DmZi4Dwyw==/me.piebridge.brevent-Vpyrv0beFPf5jUmnLjCfig==/base.apk
please report bug to https://github.com/brevent/Brevent/issues/new with logs below

<details><summary>Click to show logs</summary>

```
--- crash start ---
[command] logcat -b crash -t '08-16 19:46:13.000' -d
--------- beginning of crash
08-16 19:46:13.452 29346 29346 E AndroidRuntime: FATAL EXCEPTION: main
08-16 19:46:13.452 29346 29346 E AndroidRuntime: PID: 29346
08-16 19:46:13.452 29346 29346 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at me.piebridge.brevent.server.HΡP.μP(:3)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.do(:1)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.HН(:4)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-16 19:46:13.452 29346 29346 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: Error reporting crash
08-16 19:46:13.457 29346 29346 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:639)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:443)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:378)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5226)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5223)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:5214)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:164)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
08-16 19:46:13.457 29346 29346 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: FATAL EXCEPTION: main
08-16 19:46:14.095 29372 29372 E AndroidRuntime: PID: 29372
08-16 19:46:14.095 29372 29372 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getApplicationInfo(Ljava/lang/String;II)Landroid/content/pm/ApplicationInfo; in class Landroid/content/pm/IPackageManager; or its super classes (declaration of 'android.content.pm.IPackageManager' appears in /system/framework/framework.jar)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at me.piebridge.brevent.server.HΡP.μP(:3)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.if(:3)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at me.piebridge.brevent.server.PHΗ.HН(:11)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at me.piebridge.brevent.server.BreventServer.main(:2)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
08-16 19:46:14.095 29372 29372 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:372)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: Error reporting crash
08-16 19:46:14.097 29372 29372 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:639)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:443)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.ServiceManager.rawGetService(ServiceManager.java:378)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.os.ServiceManager.getService(ServiceManager.java:147)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5226)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.app.ActivityManager$3.create(ActivityManager.java:5223)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.util.Singleton.get(Singleton.java:43)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at android.app.ActivityManager.getService(ActivityManager.java:5214)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:164)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
08-16 19:46:14.097 29372 29372 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
--- crash end ---
--- brevent start ---
[command] logcat -b main -t '08-16 19:46:13.000' -d -s BreventLoader BreventServer
--------- beginning of main
08-16 19:46:13.543 29363 29363 I BreventLoader: sdk: 34
08-16 19:46:13.570 29365 29365 I BreventLoader: pm path me.piebridge.brevent
08-16 19:46:13.617 29365 29365 I BreventLoader: line: package:/data/app/~~63QwQ1SlhaAG_DmZi4Dwyw==/me.piebridge.brevent-Vpyrv0beFPf5jUmnLjCfig==/base.apk
08-16 19:46:13.619 29365 29365 I BreventLoader: loader path: /data/app/~~63QwQ1SlhaAG_DmZi4Dwyw==/me.piebridge.brevent-Vpyrv0beFPf5jUmnLjCfig==/base.apk
08-16 19:46:13.622 29372 29372 I BreventLoader: start: 1723823173
08-16 19:46:14.089 29372 29372 I BreventServer: args: [10, me.piebridge.brevent, 1723823173, true]
08-16 19:46:14.132 29365 29365 E BreventLoader: worker 29372 was ko, exited on signal 9
08-16 19:46:14.132 29365 29365 I BreventLoader: signal arrived, update: 0
08-16 19:46:14.132 29363 29363 I BreventLoader: worker 29365 exited with status 0
--- brevent end ---
```
</details><br/>

please report bug to https://github.com/brevent/Brevent/issues/new with logs above

**Comment by liudongmiao** [comment]
It seems you use a old version.
